<h>Numpy</h>
<p>Numpy->It is an essential python library used to perform operation especially on array</p>

In [170]:
import numpy as np
print("numpy is imported")


numpy is imported


<p>np.array->used to create an array from a list</p>

In [171]:
ls=[41,52,63]
arr=np.array(ls)
arr

array([41, 52, 63])

<p>type->used for getting the type of datastructure like list ,tuple, dictionary ,sets of the variable</p>

In [172]:
type(arr)

numpy.ndarray

In [173]:
arr*5000000

array([205000000, 260000000, 315000000])

<p>arr.ndim->used for tracing out the dimention of the array</p>

In [174]:
arr.ndim #no of dimension

1

<p>dtype->for getting the datatype of the variable</p>

In [175]:
arr.dtype

dtype('int64')

In [176]:
ls=[41,52,63,12.3]
arr=np.array(ls)
arr

array([41. , 52. , 63. , 12.3])

In [177]:
ls=[41,52,63,'upflairs']
arr=np.array(ls)
arr

array(['41', '52', '63', 'upflairs'], dtype='<U21')

In [178]:
ls=[41,52,63]
arr=np.array(ls)
arr

array([41, 52, 63])

In [179]:
arr[2] # index_address=first_address+(size_datatype*index_number)

np.int64(63)

In [180]:
ls=[41,52,63,96,85,74,5,32,52,63,46,2,52,63,1]
arr=np.array(ls)
arr

array([41, 52, 63, 96, 85, 74,  5, 32, 52, 63, 46,  2, 52, 63,  1])

In [181]:
for i in range(len(arr)):
    if arr[i]<50:
         arr[i]

In [182]:
arr[arr<50]

array([41,  5, 32, 46,  2,  1])

<p>shape->for getting the shape of array in form of rows and columns</h>

In [183]:
arr.shape

(15,)

<p>arrange->for getting 1d array in range specfied in the argument</p>

In [184]:
arr2=np.arange(50)#1d
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

<p>ones->for making n dimentional array having only 1 as an element</p>

In [185]:
np.ones((10,5,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

zeroes->for making an nd array with 0 as an element

In [186]:
np.zeros((10,5,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

linespace->for making nd array with elements between the given range with specified number of parts

In [187]:
np.linspace(1,8,5)

array([1.  , 2.75, 4.5 , 6.25, 8.  ])

random->a library in python for grtting random values.Random variable generators.

In [188]:
import random

randint()->Return random integer in range [a, b], including both end points.



In [189]:
random.randint(1,10)

1

random->Returns the values between 0 and 1.

In [190]:
random.random()

0.49730104116148677

In [191]:
ls=['arushi','nikita','pragati','yasmeen','princy','kartik','ronak']

choice->Choose a random element from a non-empty sequence.

In [192]:
random.choice(ls)#for single item

'ronak'

choices->Return a k sized list of population elements chosen with replacement.<br>
If the relative weights or cumulative weights are not specified, the selections are made with equal probability.

In [193]:
random.choices(ls,k=2)

['ronak', 'nikita']

In [194]:
ls

['arushi', 'nikita', 'pragati', 'yasmeen', 'princy', 'kartik', 'ronak']

shuffle->Shuffle list x in place, and return None.

In [195]:
random.shuffle(ls)
ls

['yasmeen', 'kartik', 'pragati', 'ronak', 'arushi', 'princy', 'nikita']

In [196]:
np.random.randint(1,50,10)

array([23,  2, 43,  4, 32,  9, 25,  3, 42, 15], dtype=int32)

In [197]:
!python --version 

Python 3.11.9


In [198]:
import numpy as np
np.random.randint(1,50,(10,2))

array([[20, 35],
       [29, 37],
       [46, 20],
       [ 1, 12],
       [20, 34],
       [ 9, 18],
       [ 2, 29],
       [37, 29],
       [17,  8],
       [45, 33]], dtype=int32)

In [199]:
arr=np.arange(60)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

reshape->reshape the array keeping the number of elements the same<br>changes the values of m and n such that the multiplication remains the same

In [200]:
arr.reshape(15,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47],
       [48, 49, 50, 51],
       [52, 53, 54, 55],
       [56, 57, 58, 59]])

resize->Return a new array with the specified shape.
If the new array is larger than the original array, then the new array is filled with repeated copies of arrar. Note that this behavior is different from a.resize(new_shape) which fills with zeros instead of repeated copies of array.

In [201]:
arr2=np.resize(arr,(25,25))
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,
         6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
        31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59,  0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
        21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45,
        46, 47, 48, 49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10,
        11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 

In [202]:
arr2.shape

(25, 25)

In [203]:
arr2.ndim

2

In [204]:
arr2.reshape(625,)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,  6,  7,
        8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
       25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58,
       59,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
       16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54, 55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,  6,
        7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
       24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
       41, 42, 43, 44, 45

ravel->changes the dimension of the array to 1d array

In [205]:
arr2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,  6,  7,
        8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
       25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58,
       59,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
       16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54, 55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,  6,
        7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
       24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
       41, 42, 43, 44, 45

In [206]:
import numpy as np

In [207]:
arr=np.random.randint(5,50,100)
arr

array([12, 44, 22, 24, 10, 13, 42, 28, 28, 13, 37, 19, 30, 30, 29, 44, 11,
        6, 26, 39, 36, 12, 16, 36, 18,  9, 48, 17, 34, 28, 20, 38,  7, 31,
       22, 17, 46, 21,  5, 18, 31, 22, 38, 27, 42, 30, 32, 39, 13, 13, 28,
       36, 26,  7, 47, 33,  8, 24,  6, 43, 31, 18, 36, 23, 12, 12, 21, 25,
       45, 44, 46,  8, 27, 39, 19, 18, 36, 31, 31, 48, 19, 18, 42, 26, 29,
       19, 18, 32, 11, 46, 20, 21, 16, 19, 14, 37, 15, 29,  9,  8],
      dtype=int32)

min->Returns the minimum element of the array

In [208]:
arr.min()

np.int32(5)

max->Returns the maximum element of the array

In [209]:
arr.max()

np.int32(48)

sum->Returns the sum of all the elements of the array 

In [210]:
arr.sum()

np.int64(2549)

mean->Returns the mean value of the array

In [211]:
arr.mean() #mean=average

np.float64(25.49)

In [212]:
arr=np.random.randint(5,50,(4,3))
arr

array([[27, 27, 38],
       [12, 45, 41],
       [20, 44, 29],
       [36, 12, 22]], dtype=int32)

In [213]:
arr.shape

(4, 3)

transpose->gives the transpose of the nd array

In [214]:
np.transpose(arr)

array([[27, 12, 20, 36],
       [27, 45, 44, 12],
       [38, 41, 29, 22]], dtype=int32)

In [215]:
np.transpose(arr).shape

(3, 4)

In [216]:
arr.T #same as transpose

array([[27, 12, 20, 36],
       [27, 45, 44, 12],
       [38, 41, 29, 22]], dtype=int32)

In [217]:
arr=np.random.randint(2,12,(10,5))
arr

array([[ 7, 10,  5, 11, 11],
       [ 2,  4,  4,  2,  4],
       [10, 11, 10,  9,  6],
       [ 9,  2,  4,  3,  9],
       [ 5,  2, 11,  2,  3],
       [11,  9,  8,  9,  9],
       [ 8,  6,  3,  3,  6],
       [ 2,  6,  9,  4,  7],
       [ 7, 10, 10,  5,  9],
       [ 6,  5,  2,  8, 11]], dtype=int32)

flatten->converts the nd array into 1d array

In [218]:
arr.flatten()

array([ 7, 10,  5, 11, 11,  2,  4,  4,  2,  4, 10, 11, 10,  9,  6,  9,  2,
        4,  3,  9,  5,  2, 11,  2,  3, 11,  9,  8,  9,  9,  8,  6,  3,  3,
        6,  2,  6,  9,  4,  7,  7, 10, 10,  5,  9,  6,  5,  2,  8, 11],
      dtype=int32)

In [219]:
arr.ravel()

array([ 7, 10,  5, 11, 11,  2,  4,  4,  2,  4, 10, 11, 10,  9,  6,  9,  2,
        4,  3,  9,  5,  2, 11,  2,  3, 11,  9,  8,  9,  9,  8,  6,  3,  3,
        6,  2,  6,  9,  4,  7,  7, 10, 10,  5,  9,  6,  5,  2,  8, 11],
      dtype=int32)

In [220]:
arr.reshape(50,)

array([ 7, 10,  5, 11, 11,  2,  4,  4,  2,  4, 10, 11, 10,  9,  6,  9,  2,
        4,  3,  9,  5,  2, 11,  2,  3, 11,  9,  8,  9,  9,  8,  6,  3,  3,
        6,  2,  6,  9,  4,  7,  7, 10, 10,  5,  9,  6,  5,  2,  8, 11],
      dtype=int32)

In [221]:
np.resize(arr,(50,))

array([ 7, 10,  5, 11, 11,  2,  4,  4,  2,  4, 10, 11, 10,  9,  6,  9,  2,
        4,  3,  9,  5,  2, 11,  2,  3, 11,  9,  8,  9,  9,  8,  6,  3,  3,
        6,  2,  6,  9,  4,  7,  7, 10, 10,  5,  9,  6,  5,  2,  8, 11],
      dtype=int32)

In [222]:
arr.reshape(10,5)

array([[ 7, 10,  5, 11, 11],
       [ 2,  4,  4,  2,  4],
       [10, 11, 10,  9,  6],
       [ 9,  2,  4,  3,  9],
       [ 5,  2, 11,  2,  3],
       [11,  9,  8,  9,  9],
       [ 8,  6,  3,  3,  6],
       [ 2,  6,  9,  4,  7],
       [ 7, 10, 10,  5,  9],
       [ 6,  5,  2,  8, 11]], dtype=int32)

In [223]:
arr[0]

array([ 7, 10,  5, 11, 11], dtype=int32)

In [224]:
arr[-1,0]

np.int32(6)

In [225]:
arr[2:5]

array([[10, 11, 10,  9,  6],
       [ 9,  2,  4,  3,  9],
       [ 5,  2, 11,  2,  3]], dtype=int32)

In [226]:
arr[7:10]

array([[ 2,  6,  9,  4,  7],
       [ 7, 10, 10,  5,  9],
       [ 6,  5,  2,  8, 11]], dtype=int32)

In [227]:
arr[7:10,0:2]

array([[ 2,  6],
       [ 7, 10],
       [ 6,  5]], dtype=int32)

In [228]:
arr[0:10,0:2]

array([[ 7, 10],
       [ 2,  4],
       [10, 11],
       [ 9,  2],
       [ 5,  2],
       [11,  9],
       [ 8,  6],
       [ 2,  6],
       [ 7, 10],
       [ 6,  5]], dtype=int32)

In [229]:
arr[0:,0:2]

array([[ 7, 10],
       [ 2,  4],
       [10, 11],
       [ 9,  2],
       [ 5,  2],
       [11,  9],
       [ 8,  6],
       [ 2,  6],
       [ 7, 10],
       [ 6,  5]], dtype=int32)

In [230]:
arr[-5:-2,-3:]

array([[8, 9, 9],
       [3, 3, 6],
       [9, 4, 7]], dtype=int32)

In [231]:
arr[0::2,2:6:2]

array([[ 5, 11],
       [10,  6],
       [11,  3],
       [ 3,  6],
       [10,  9]], dtype=int32)

In [232]:
import numpy as np
import random
arr=np.random.randint(2,50,(5,10,5))
arr


array([[[ 6, 23, 33, 46, 30],
        [ 7,  5, 33, 32,  7],
        [ 9, 16, 22, 34, 22],
        [27, 18, 10, 27, 11],
        [40, 46, 35, 13,  7],
        [37, 17, 29, 44, 32],
        [14, 34, 32, 17, 13],
        [ 2, 13, 42,  9, 26],
        [30, 46, 39, 16, 28],
        [32,  9, 24,  5, 32]],

       [[42, 48, 15, 41, 23],
        [36, 21, 10, 45,  3],
        [41, 44, 14, 41,  9],
        [34, 32, 21, 26, 42],
        [42,  8, 17, 40,  3],
        [11, 23, 10, 20, 43],
        [41, 35, 34, 37, 35],
        [44, 31,  6, 31, 32],
        [29, 29, 40, 19, 42],
        [37, 45, 20, 35, 25]],

       [[21,  3, 40, 40,  9],
        [10, 25, 25,  8,  5],
        [27, 23, 40, 36, 26],
        [43, 49, 42, 29,  9],
        [32,  3, 49, 48, 44],
        [14, 20, 43, 23, 43],
        [30, 48, 43, 36,  2],
        [42, 17, 18, 20, 34],
        [ 6, 45, 12, 36, 23],
        [47,  5, 48, 28, 32]],

       [[17, 39,  5, 32, 27],
        [42, 28, 15,  8, 33],
        [10, 47, 29, 40, 19],
    

In [233]:
arr.shape

(5, 10, 5)

In [234]:
arr.ndim

3

In [235]:
arr[0]

array([[ 6, 23, 33, 46, 30],
       [ 7,  5, 33, 32,  7],
       [ 9, 16, 22, 34, 22],
       [27, 18, 10, 27, 11],
       [40, 46, 35, 13,  7],
       [37, 17, 29, 44, 32],
       [14, 34, 32, 17, 13],
       [ 2, 13, 42,  9, 26],
       [30, 46, 39, 16, 28],
       [32,  9, 24,  5, 32]], dtype=int32)

In [236]:
arr[0,8:,2:]

array([[39, 16, 28],
       [24,  5, 32]], dtype=int32)

In [237]:
arr[:6:,9,0:6]

array([[32,  9, 24,  5, 32],
       [37, 45, 20, 35, 25],
       [47,  5, 48, 28, 32],
       [41, 47, 13, 45, 21],
       [37, 14, 12,  7, 45]], dtype=int32)

In [238]:
arr=np.array([7,5,9])
arr

array([7, 5, 9])

In [239]:
arr.argsort()

array([1, 0, 2])

In [240]:
arr.max()

np.int64(9)

argmax->shows the index of maximum item

In [241]:
arr.argmax()#shows the index of maximum item

np.int64(2)

argmin->shows the index of minimum item

In [242]:
arr.argmin()#shows the index of minimum item

np.int64(1)

sort->sort the array in-place and returns none

In [243]:
arr.sort()

In [244]:
arr

array([5, 7, 9])

argsort->returns the original index of the elements after sorting and returns a list

In [245]:
arr.argsort()

array([0, 1, 2])

In [246]:
arr

array([5, 7, 9])

In [247]:
arr=np.random.randint(2,12,(10,5))
arr

array([[ 2,  3,  9, 11,  5],
       [11,  9,  2,  2,  2],
       [ 2,  9,  7,  3,  3],
       [ 2,  9,  8,  7,  8],
       [ 5, 11,  4,  9,  3],
       [ 6,  9,  7,  5,  4],
       [ 4,  4,  3,  7, 11],
       [ 9,  9,  2,  2,  4],
       [ 8,  4,  4,  2,  4],
       [ 5,  5,  8, 11,  7]], dtype=int32)

In [248]:
arr=[1,2,2,3,3,4,5,6]

unique->returns the unique elements of the array in an array

In [249]:
np.unique(arr)

array([1, 2, 3, 4, 5, 6])

In [250]:
np.random.randint(2,250,200)

array([131, 158,  79,  98, 191, 169, 125, 117,  53, 227,  76, 232,   4,
       211, 127, 174,  36,  75,  14, 155, 119, 185, 169, 177,  68,  23,
       138, 106, 201, 215, 245, 246, 174, 138, 122,  57,  47, 154, 240,
       214, 227, 239, 146, 106,  13, 121, 109,  67,  75,  37,  67, 127,
        84, 237,  96, 178,  11,  67, 249,  85, 194,  61, 212, 166, 127,
        41,  75, 169, 232,  29, 243, 113,  23, 126, 249, 106,  42, 135,
       200,  12, 249, 188, 141,  10,  38, 169,  70, 171, 131,  46, 241,
       211, 219, 234, 205,  65,  31,  99, 178, 141, 173,   5, 190, 227,
        32, 180,  43,   2, 189,  21,  52, 168, 187,  80, 202, 189, 183,
       215,  31, 204, 213, 104, 171,  15, 238, 182, 173, 212, 146,   7,
       106, 183, 134,   4, 177, 179,  76, 170,  30,  44, 216, 170,  83,
       233, 116,  90,  18, 238, 151, 249, 162,  73, 201, 115,  37, 218,
       133,  67, 204, 241, 240,  82, 118,  45, 229, 177, 104,  27,  58,
       162,  32,  86, 241,  71,  76, 127,  34,  19,  29,  44,  2

median->Returns the median of the array

In [251]:
np.median(arr)

np.float64(3.0)

var->Returns the varience of the elements in the array

In [252]:
np.var(arr)

np.float64(2.4375)

std->returns the standard deviation of the array which is square root of varience

In [253]:
np.std(arr)

np.float64(1.5612494995995996)

sqrt->Returns the square root of array

In [254]:
np.sqrt(25)

np.float64(5.0)

In [255]:
#pandas

In [256]:
!pip install pandas


[notice] A new release of pip is available: 24.0 -> 24.1.2
[notice] To update, run: C:\Users\DeLL\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [257]:
!pip install pandas


[notice] A new release of pip is available: 24.0 -> 24.1.2
[notice] To update, run: C:\Users\DeLL\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


pandas->It is an essential library in python used in data science helps to read relational files or tabular form of database files like exel-csv,sql etc

In [258]:
import pandas as pd
print("imported")

imported


In [259]:
dt = {"Name":['Nikita rawat','pragati sharama','kartik','arushi'],
     "Branch":['cse','it','ece','cse'],
     "class":[1,2,3,4],
     "city":['ajmer','agra','mathura','vridavan']}
dt




{'Name': ['Nikita rawat', 'pragati sharama', 'kartik', 'arushi'],
 'Branch': ['cse', 'it', 'ece', 'cse'],
 'class': [1, 2, 3, 4],
 'city': ['ajmer', 'agra', 'mathura', 'vridavan']}

DataFrame->Two-dimensional, size-mutable, potentially heterogeneous tabular data.<br>The primary pandas data structure.

In [260]:
dt=pd.DataFrame(dt)
dt


Name Branch  class      city
0     Nikita rawat    cse      1     ajmer
1  pragati sharama     it      2      agra
2           kartik    ece      3   mathura
3           arushi    cse      4  vridavan

In [261]:
type(dt)

pandas.core.frame.DataFrame

In [262]:
dt["Name"]

0       Nikita rawat
1    pragati sharama
2             kartik
3             arushi
Name: Name, dtype: object

In [263]:
type(dt["Name"])

pandas.core.series.Series

read_csv->reads file with csv extension.<br>There are more types of files which can be read but we are working with csv file

In [264]:
df= pd.read_csv('Used_Bikes.csv')
df

bike_name     price       city  kms_driven  \
0        TVS Star City Plus Dual Tone 110cc   35000.0  Ahmedabad     17654.0   
1               Royal Enfield Classic 350cc  119900.0      Delhi     11000.0   
2                      Triumph Daytona 675R  600000.0      Delhi       110.0   
3                      TVS Apache RTR 180cc   65000.0  Bangalore     16329.0   
4      Yamaha FZ S V 2.0 150cc-Ltd. Edition   80000.0  Bangalore     10000.0   
...                                     ...       ...        ...         ...   
32643                Hero Passion Pro 100cc   39000.0      Delhi     22000.0   
32644                  TVS Apache RTR 180cc   30000.0     Karnal      6639.0   
32645              Bajaj Avenger Street 220   60000.0      Delhi     20373.0   
32646             Hero Super Splendor 125cc   15600.0     Jaipur     84186.0   
32647                    Bajaj Pulsar 150cc   22000.0       Pune     60857.0   

             owner   age  power          brand  
0      First Owner   3.0  110.0            TVS  
1      First Owner   4.0  350.0  Royal Enfield  
2      First Owner   8.0  675.0        Triumph  
3      First Owner   4.0  180.0            TVS  
4      First Owner   3.0  150.0         Yamaha  
...            ...   ...    ...            ...  
32643  First Owner   4.0  100.0           Hero  
32644  First Owner   9.0  180.0            TVS  
32645  First Owner   6.0  220.0          Bajaj  
32646  First Owner  16.0  125.0           Hero  
32647  First Owner  13.0  150.0          Bajaj  

[32648 rows x 8 columns]

head->Return the first n rows.<br>by default returns first 5

In [265]:
df.head(20)

bike_name     price       city  kms_driven  \
0         TVS Star City Plus Dual Tone 110cc   35000.0  Ahmedabad     17654.0   
1                Royal Enfield Classic 350cc  119900.0      Delhi     11000.0   
2                       Triumph Daytona 675R  600000.0      Delhi       110.0   
3                       TVS Apache RTR 180cc   65000.0  Bangalore     16329.0   
4       Yamaha FZ S V 2.0 150cc-Ltd. Edition   80000.0  Bangalore     10000.0   
5                           Yamaha FZs 150cc   53499.0      Delhi     25000.0   
6              Honda CB Hornet 160R  ABS DLX   85000.0      Delhi      8200.0   
7        Hero Splendor Plus Self Alloy 100cc   45000.0      Delhi     12645.0   
8          Royal Enfield Thunderbird X 350cc  145000.0  Bangalore      9190.0   
9   Royal Enfield Classic Desert Storm 500cc   88000.0      Delhi     19000.0   
10                  Yamaha YZF-R15 2.0 150cc   72000.0  Bangalore     20000.0   
11                         Yamaha FZ25 250cc   95000.0  Bangalore      9665.0   
12                        Bajaj Pulsar NS200   78000.0  Bangalore      9900.0   
13                       Bajaj Discover 100M   29499.0      Delhi     20000.0   
14                       Bajaj Discover 125M   29900.0      Delhi     20000.0   
15                    Bajaj Pulsar NS200 ABS   90000.0  Bangalore     11574.0   
16                    Bajaj Pulsar RS200 ABS  120000.0  Bangalore     23000.0   
17                    Suzuki Gixxer SF 150cc   48000.0     Mumbai     24725.0   
18                        Benelli 302R 300CC  240000.0     Mumbai     15025.0   
19                       Bajaj Discover 125M   29900.0      Delhi     20000.0   

           owner  age  power          brand  
0    First Owner  3.0  110.0            TVS  
1    First Owner  4.0  350.0  Royal Enfield  
2    First Owner  8.0  675.0        Triumph  
3    First Owner  4.0  180.0            TVS  
4    First Owner  3.0  150.0         Yamaha  
5    First Owner  6.0  150.0         Yamaha  
6    First Owner  3.0  160.0          Honda  
7    First Owner  3.0  100.0           Hero  
8    First Owner  3.0  350.0  Royal Enfield  
9   Second Owner  7.0  500.0  Royal Enfield  
10   First Owner  7.0  150.0         Yamaha  
11   First Owner  4.0  250.0         Yamaha  
12   First Owner  4.0  200.0          Bajaj  
13   First Owner  8.0  100.0          Bajaj  
14   First Owner  7.0  125.0          Bajaj  
15   First Owner  3.0  200.0          Bajaj  
16   First Owner  3.0  200.0          Bajaj  
17   First Owner  5.0  150.0         Suzuki  
18  Second Owner  3.0  302.0        Benelli  
19   First Owner  7.0  125.0          Bajaj

tail->Return the last n rows.<br>by default returns the last 5 rows

In [266]:
df.tail(10)

bike_name     price         city  kms_driven  \
32638        Yamaha Fazer 25 250cc  123000.0       Kadapa     14500.0   
32639  Royal Enfield Classic 350cc   95500.0        Delhi     18000.0   
32640       Hero Passion Pro 100cc   32000.0        Delhi     12000.0   
32641          Bajaj Avenger 220cc   41000.0        Delhi     20245.0   
32642           Hero Passion 100cc   15000.0  Perumbavoor     35000.0   
32643       Hero Passion Pro 100cc   39000.0        Delhi     22000.0   
32644         TVS Apache RTR 180cc   30000.0       Karnal      6639.0   
32645     Bajaj Avenger Street 220   60000.0        Delhi     20373.0   
32646    Hero Super Splendor 125cc   15600.0       Jaipur     84186.0   
32647           Bajaj Pulsar 150cc   22000.0         Pune     60857.0   

              owner   age  power          brand  
32638   First Owner   4.0  250.0         Yamaha  
32639   First Owner   8.0  350.0  Royal Enfield  
32640   First Owner   6.0  100.0           Hero  
32641  Second Owner  11.0  220.0          Bajaj  
32642  Second Owner  19.0  100.0           Hero  
32643   First Owner   4.0  100.0           Hero  
32644   First Owner   9.0  180.0            TVS  
32645   First Owner   6.0  220.0          Bajaj  
32646   First Owner  16.0  125.0           Hero  
32647   First Owner  13.0  150.0          Bajaj

info->Print a concise summary of a DataFrame.<br>
This method prints information about a DataFrame including the index dtype and columns, non-null values and memory usage.

In [267]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32648 entries, 0 to 32647
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   bike_name   32648 non-null  object 
 1   price       32648 non-null  float64
 2   city        32648 non-null  object 
 3   kms_driven  32648 non-null  float64
 4   owner       32648 non-null  object 
 5   age         32648 non-null  float64
 6   power       32648 non-null  float64
 7   brand       32648 non-null  object 
dtypes: float64(4), object(4)
memory usage: 2.0+ MB


In [268]:
## accessing
df.price

0         35000.0
1        119900.0
2        600000.0
3         65000.0
4         80000.0
           ...   
32643     39000.0
32644     30000.0
32645     60000.0
32646     15600.0
32647     22000.0
Name: price, Length: 32648, dtype: float64

In [269]:
df["price"]

0         35000.0
1        119900.0
2        600000.0
3         65000.0
4         80000.0
           ...   
32643     39000.0
32644     30000.0
32645     60000.0
32646     15600.0
32647     22000.0
Name: price, Length: 32648, dtype: float64

In [270]:
type(df['price'])

pandas.core.series.Series

In [271]:
df[["price"]]#dataframe

price
0       35000.0
1      119900.0
2      600000.0
3       65000.0
4       80000.0
...         ...
32643   39000.0
32644   30000.0
32645   60000.0
32646   15600.0
32647   22000.0

[32648 rows x 1 columns]

In [272]:
df[['price','city','brand']]

price       city          brand
0       35000.0  Ahmedabad            TVS
1      119900.0      Delhi  Royal Enfield
2      600000.0      Delhi        Triumph
3       65000.0  Bangalore            TVS
4       80000.0  Bangalore         Yamaha
...         ...        ...            ...
32643   39000.0      Delhi           Hero
32644   30000.0     Karnal            TVS
32645   60000.0      Delhi          Bajaj
32646   15600.0     Jaipur           Hero
32647   22000.0       Pune          Bajaj

[32648 rows x 3 columns]

loc->Access a group of rows and columns by label(s) or a boolean array.


In [273]:
#loc & iloc
df.loc[10:20,['price','bike_name']]

price                 bike_name
10   72000.0  Yamaha YZF-R15 2.0 150cc
11   95000.0         Yamaha FZ25 250cc
12   78000.0        Bajaj Pulsar NS200
13   29499.0       Bajaj Discover 100M
14   29900.0       Bajaj Discover 125M
15   90000.0    Bajaj Pulsar NS200 ABS
16  120000.0    Bajaj Pulsar RS200 ABS
17   48000.0    Suzuki Gixxer SF 150cc
18  240000.0        Benelli 302R 300CC
19   29900.0       Bajaj Discover 125M
20  120000.0    Bajaj Pulsar RS200 ABS

In [274]:
df.loc[20:35,['owner','age','power','brand']]

owner   age  power          brand
20   First Owner   3.0  200.0          Bajaj
21   First Owner   5.0  150.0         Suzuki
22   First Owner   2.0  110.0           Hero
23   First Owner   5.0  500.0  Royal Enfield
24   First Owner   6.0  150.0         Yamaha
25   First Owner   4.0  200.0          Bajaj
26   First Owner  16.0  125.0           Hero
27  Second Owner   7.0  125.0          Honda
28   First Owner   8.0  150.0          Bajaj
29   First Owner   2.0  160.0          Honda
30   First Owner   3.0  200.0          Bajaj
31  Second Owner   4.0  150.0         Yamaha
32   First Owner   6.0  220.0          Bajaj
33   First Owner   4.0  390.0            KTM
34   First Owner   8.0  150.0          Honda
35  Second Owner   8.0  200.0            KTM

In [275]:
df

bike_name     price       city  kms_driven  \
0        TVS Star City Plus Dual Tone 110cc   35000.0  Ahmedabad     17654.0   
1               Royal Enfield Classic 350cc  119900.0      Delhi     11000.0   
2                      Triumph Daytona 675R  600000.0      Delhi       110.0   
3                      TVS Apache RTR 180cc   65000.0  Bangalore     16329.0   
4      Yamaha FZ S V 2.0 150cc-Ltd. Edition   80000.0  Bangalore     10000.0   
...                                     ...       ...        ...         ...   
32643                Hero Passion Pro 100cc   39000.0      Delhi     22000.0   
32644                  TVS Apache RTR 180cc   30000.0     Karnal      6639.0   
32645              Bajaj Avenger Street 220   60000.0      Delhi     20373.0   
32646             Hero Super Splendor 125cc   15600.0     Jaipur     84186.0   
32647                    Bajaj Pulsar 150cc   22000.0       Pune     60857.0   

             owner   age  power          brand  
0      First Owner   3.0  110.0            TVS  
1      First Owner   4.0  350.0  Royal Enfield  
2      First Owner   8.0  675.0        Triumph  
3      First Owner   4.0  180.0            TVS  
4      First Owner   3.0  150.0         Yamaha  
...            ...   ...    ...            ...  
32643  First Owner   4.0  100.0           Hero  
32644  First Owner   9.0  180.0            TVS  
32645  First Owner   6.0  220.0          Bajaj  
32646  First Owner  16.0  125.0           Hero  
32647  First Owner  13.0  150.0          Bajaj  

[32648 rows x 8 columns]

iloc->Purely integer-location based indexing for selection by position
disadvantage->it can only access the columns in range not from betwwen like loc

In [276]:
df.iloc[20:35,0:3:2]

bike_name       city
20               Bajaj Pulsar RS200 ABS  Bangalore
21               Suzuki Gixxer SF 150cc     Mumbai
22  Hero Splendor iSmart Plus IBS 110cc      Delhi
23   Royal Enfield Classic Chrome 500cc     Kalyan
24                Yamaha FZ V 2.0 150cc      Delhi
25                   Bajaj Pulsar NS200  Bangalore
26            Hero Super Splendor 125cc  Ahmedabad
27              Honda CBF Stunner 125cc  Faridabad
28                   Bajaj Pulsar 150cc  Bangalore
29              Honda X-Blade 160CC ABS     Mettur
30                   Bajaj Pulsar NS200  Hyderabad
31             Yamaha YZF-R15 2.0 150cc    Kaithal
32                  Bajaj Avenger 220cc    Gurgaon
33                         KTM RC 390cc       Pune
34               Honda CB Unicorn 150cc      Noida

min->Return the minimum of the values over the requested axis.



In [277]:
df['price'].min()

np.float64(4400.0)

max->Return the maximum of the values over the requested axis.

In [278]:
df['price'].max()

np.float64(1900000.0)

mean->Return the mean of the values over the requested axis.

In [279]:
df['price'].mean()

np.float64(68295.41763660868)

median->Return the median of the values over the requested axis.

In [280]:
df['price'].median()

np.float64(43000.0)

columns->returns all th column values

In [281]:
df.columns

Index(['bike_name', 'price', 'city', 'kms_driven', 'owner', 'age', 'power',
       'brand'],
      dtype='object')

In [282]:
df.columns=['bike_name', 'price', 'city', 'kms_driven', 'owner', 'age', 'power',
      'brand']
df.columns

Index(['bike_name', 'price', 'city', 'kms_driven', 'owner', 'age', 'power',
       'brand'],
      dtype='object')

In [283]:
df.shape#no of rows and no of columns

(32648, 8)

In [284]:
df.dtypes #datatypes of each column

bike_name      object
price         float64
city           object
kms_driven    float64
owner          object
age           float64
power         float64
brand          object
dtype: object

In [285]:
udr_50k=df[df['price']<=50000]
udr_50k.head()#by default 5
     

bike_name    price       city  kms_driven  \
0    TVS Star City Plus Dual Tone 110cc  35000.0  Ahmedabad     17654.0   
7   Hero Splendor Plus Self Alloy 100cc  45000.0      Delhi     12645.0   
13                  Bajaj Discover 100M  29499.0      Delhi     20000.0   
14                  Bajaj Discover 125M  29900.0      Delhi     20000.0   
17               Suzuki Gixxer SF 150cc  48000.0     Mumbai     24725.0   

          owner  age  power   brand  
0   First Owner  3.0  110.0     TVS  
7   First Owner  3.0  100.0    Hero  
13  First Owner  8.0  100.0   Bajaj  
14  First Owner  7.0  125.0   Bajaj  
17  First Owner  5.0  150.0  Suzuki

In [286]:
udr_50k['price'].max()

np.float64(50000.0)

In [287]:
udr_50k.shape

(19114, 8)

value_counts->Return a Series containing counts of unique values.

In [288]:
udr_50k['brand'].value_counts()

brand
Bajaj            7143
Hero             6258
Yamaha           2250
Suzuki           1295
Honda            1178
TVS               936
Mahindra           31
Royal Enfield      22
LML                 1
Name: count, dtype: int64

In [289]:
udr_50k['owner'].value_counts()

owner
First Owner             17447
Second Owner             1604
Third Owner                57
Fourth Owner Or More        6
Name: count, dtype: int64

In [290]:
udr_50k_first=udr_50k[udr_50k['owner']=="First Owner"]
udr_50k_first.head()

bike_name    price       city  kms_driven  \
0    TVS Star City Plus Dual Tone 110cc  35000.0  Ahmedabad     17654.0   
7   Hero Splendor Plus Self Alloy 100cc  45000.0      Delhi     12645.0   
13                  Bajaj Discover 100M  29499.0      Delhi     20000.0   
14                  Bajaj Discover 125M  29900.0      Delhi     20000.0   
17               Suzuki Gixxer SF 150cc  48000.0     Mumbai     24725.0   

          owner  age  power   brand  
0   First Owner  3.0  110.0     TVS  
7   First Owner  3.0  100.0    Hero  
13  First Owner  8.0  100.0   Bajaj  
14  First Owner  7.0  125.0   Bajaj  
17  First Owner  5.0  150.0  Suzuki

In [291]:
udr_50k_first[['price']].min()

price    4400.0
dtype: float64

In [292]:
udr_50k_first[udr_50k_first['price']==4400]

bike_name   price     city  kms_driven        owner   age  \
4960  LML Freedom DX 110cc  4400.0  Godhara     55000.0  First Owner  16.0   

      power brand  
4960  110.0   LML

In [293]:
udr_50k_first['brand'].value_counts()

brand
Bajaj            6356
Hero             5541
Yamaha           2187
Suzuki           1286
Honda            1131
TVS               905
Mahindra           27
Royal Enfield      13
LML                 1
Name: count, dtype: int64

unique->Return unique values of Series object.

In [294]:
udr_50k_first['brand'].unique()

array(['TVS', 'Hero', 'Bajaj', 'Suzuki', 'Yamaha', 'Honda', 'Mahindra',
       'Royal Enfield', 'LML'], dtype=object)

nunique->Return number of unique elements in the object.<br>
Excludes NA values by default.

In [295]:
udr_50k_first['brand'].nunique()

9

In [296]:
df['brand'].nunique()

23

In [297]:
df['brand'].unique()

array(['TVS', 'Royal Enfield', 'Triumph', 'Yamaha', 'Honda', 'Hero',
       'Bajaj', 'Suzuki', 'Benelli', 'KTM', 'Mahindra', 'Kawasaki',
       'Ducati', 'Hyosung', 'Harley-Davidson', 'Jawa', 'BMW', 'Indian',
       'Rajdoot', 'LML', 'Yezdi', 'MV', 'Ideal'], dtype=object)

&->returns true if all the conditions are true

In [298]:
dt=df[(df['price']<=100000)&(df['owner']=='First Owner') & (df['age']<=2)&(df['brand']=="Bajaj")]
dt


bike_name    price        city  kms_driven  \
95                  Bajaj Pulsar 150cc  60000.0        Pune      2000.0   
340        Bajaj Pulsar 125cc Disc CBS  47000.0       Banki     14009.0   
341           Bajaj Avenger Street 220  95000.0       Delhi     11000.0   
510                 Bajaj Pulsar 150cc  66000.0       Delhi     15000.0   
619           Bajaj V15 150cc POWER UP  35000.0      Mumbai     26000.0   
889   Bajaj Pulsar 150cc Rear Disc ABS  85000.0    Balaghat      2500.0   
1340         Bajaj Discover 125cc Disc  39000.0   Faridabad      9923.0   
1401                Bajaj Pulsar 150cc  67000.0     Chennai      6266.0   
1423                Bajaj Pulsar 150cc  67000.0     Chennai      6266.0   
1445         Bajaj Discover 125cc Disc  39000.0   Faridabad      9923.0   
1818             Bajaj CT 100 ES Alloy  39000.0   Faridabad      2564.0   
1819     Bajaj Platina  Alloy ES-100cc  39000.0   Faridabad     12193.0   
1849     Bajaj Platina  Alloy ES-100cc  39000.0   Faridabad     12193.0   
1893     Bajaj Platina  Alloy ES-100cc  38000.0   Faridabad     12692.0   
2173               Bajaj Platina 100cc  39000.0   Faridabad      8491.0   
2185     Bajaj Platina 110 H Gear Disc  43500.0      Jaipur     18346.0   
2782             Bajaj Platina 110 CBS  47000.0     Gurgaon      2860.0   
2838      Bajaj Avenger Cruise 220 ABS  99000.0       Delhi      1958.0   
2852             Bajaj Platina 110 CBS  47000.0     Gurgaon      2860.0   
3101              Bajaj CT110 ES Alloy  48000.0   Bangalore      1850.0   
3134             Bajaj CT 100 ES Alloy  32000.0   Faridabad     12000.0   
3175      Bajaj Avenger Street 160 ABS  85000.0      Mumbai      7000.0   
3197      Bajaj Avenger Street 160 ABS  85000.0      Mumbai      7000.0   
3209             Bajaj CT 100 ES Alloy  32000.0   Faridabad     12000.0   
3948      Bajaj Avenger Street 160 ABS  80000.0       Delhi      2700.0   
4424             Bajaj Platina 110 CBS  39500.0   Faridabad     14268.0   
4959             Bajaj Platina 110 CBS  55000.0   Ahmedabad      5200.0   
5046                Bajaj Pulsar 150cc  60000.0   Ghaziabad      7312.0   
5477          Bajaj Avenger Cruise 220  85000.0    Falakata      4500.0   
5578                 Bajaj Pulsar 220F  93500.0       Thane       199.0   
5707      Bajaj Pulsar NS160 Rear Disc  85000.0     Silchar      3000.0   
6516          Bajaj Avenger Street 180  65000.0   Faridabad      6903.0   
6532               Bajaj Platina 100cc  38000.0   Faridabad     15383.0   
6992      Bajaj Avenger Street 160 ABS  80000.0       Delhi      3509.0   
7167               Bajaj Platina 100cc  38000.0   Faridabad     15383.0   
7272             Bajaj CT 100 ES Alloy  38500.0   Faridabad      4877.0   
7323          Bajaj Avenger Cruise 220  85000.0    Falakata      4500.0   
7354                Bajaj Pulsar 150cc  60000.0   Faridabad     10121.0   
7835             Bajaj CT 100 KS Alloy  40000.0  Chandigarh      1501.0   
8107      Bajaj Pulsar NS160 Rear Disc  97000.0    Tiruppur        78.0   
8335           Bajaj Pulsar 150cc Neon  72000.0        Pune      3162.0   

            owner  age  power  brand  
95    First Owner  2.0  150.0  Bajaj  
340   First Owner  2.0  125.0  Bajaj  
341   First Owner  2.0  220.0  Bajaj  
510   First Owner  2.0  150.0  Bajaj  
619   First Owner  2.0  150.0  Bajaj  
889   First Owner  2.0  150.0  Bajaj  
1340  First Owner  2.0  125.0  Bajaj  
1401  First Owner  2.0  150.0  Bajaj  
1423  First Owner  2.0  150.0  Bajaj  
1445  First Owner  2.0  125.0  Bajaj  
1818  First Owner  2.0  100.0  Bajaj  
1819  First Owner  2.0  100.0  Bajaj  
1849  First Owner  2.0  100.0  Bajaj  
1893  First Owner  2.0  100.0  Bajaj  
2173  First Owner  2.0  100.0  Bajaj  
2185  First Owner  2.0  110.0  Bajaj  
2782  First Owner  2.0  110.0  Bajaj  
2838  First Owner  2.0  220.0  Bajaj  
2852  First Owner  2.0  110.0  Bajaj  
3101  First Owner  2.0  110.0  Bajaj  
3134  First Owner  2.0  100.0  Bajaj  
3175  First Owner  2

In [299]:
dt['brand'].value_counts()

brand
Bajaj    41
Name: count, dtype: int64

In [300]:
import pandas as pd
df= pd.read_csv('Used_Bikes.csv')
df

bike_name     price       city  kms_driven  \
0        TVS Star City Plus Dual Tone 110cc   35000.0  Ahmedabad     17654.0   
1               Royal Enfield Classic 350cc  119900.0      Delhi     11000.0   
2                      Triumph Daytona 675R  600000.0      Delhi       110.0   
3                      TVS Apache RTR 180cc   65000.0  Bangalore     16329.0   
4      Yamaha FZ S V 2.0 150cc-Ltd. Edition   80000.0  Bangalore     10000.0   
...                                     ...       ...        ...         ...   
32643                Hero Passion Pro 100cc   39000.0      Delhi     22000.0   
32644                  TVS Apache RTR 180cc   30000.0     Karnal      6639.0   
32645              Bajaj Avenger Street 220   60000.0      Delhi     20373.0   
32646             Hero Super Splendor 125cc   15600.0     Jaipur     84186.0   
32647                    Bajaj Pulsar 150cc   22000.0       Pune     60857.0   

             owner   age  power          brand  
0      First Owner   3.0  110.0            TVS  
1      First Owner   4.0  350.0  Royal Enfield  
2      First Owner   8.0  675.0        Triumph  
3      First Owner   4.0  180.0            TVS  
4      First Owner   3.0  150.0         Yamaha  
...            ...   ...    ...            ...  
32643  First Owner   4.0  100.0           Hero  
32644  First Owner   9.0  180.0            TVS  
32645  First Owner   6.0  220.0          Bajaj  
32646  First Owner  16.0  125.0           Hero  
32647  First Owner  13.0  150.0          Bajaj  

[32648 rows x 8 columns]

In [301]:
df.head()

bike_name     price       city  kms_driven  \
0    TVS Star City Plus Dual Tone 110cc   35000.0  Ahmedabad     17654.0   
1           Royal Enfield Classic 350cc  119900.0      Delhi     11000.0   
2                  Triumph Daytona 675R  600000.0      Delhi       110.0   
3                  TVS Apache RTR 180cc   65000.0  Bangalore     16329.0   
4  Yamaha FZ S V 2.0 150cc-Ltd. Edition   80000.0  Bangalore     10000.0   

         owner  age  power          brand  
0  First Owner  3.0  110.0            TVS  
1  First Owner  4.0  350.0  Royal Enfield  
2  First Owner  8.0  675.0        Triumph  
3  First Owner  4.0  180.0            TVS  
4  First Owner  3.0  150.0         Yamaha

In [302]:
#
df.dtypes
#numerical and categorical

bike_name      object
price         float64
city           object
kms_driven    float64
owner          object
age           float64
power         float64
brand          object
dtype: object

In [303]:
df[['price','kms_driven','age','power']]

price  kms_driven   age  power
0       35000.0     17654.0   3.0  110.0
1      119900.0     11000.0   4.0  350.0
2      600000.0       110.0   8.0  675.0
3       65000.0     16329.0   4.0  180.0
4       80000.0     10000.0   3.0  150.0
...         ...         ...   ...    ...
32643   39000.0     22000.0   4.0  100.0
32644   30000.0      6639.0   9.0  180.0
32645   60000.0     20373.0   6.0  220.0
32646   15600.0     84186.0  16.0  125.0
32647   22000.0     60857.0  13.0  150.0

[32648 rows x 4 columns]

select_dtypes->Return a subset of the DataFrame's columns based on the column dtypes.

In [304]:
catgorical=df.select_dtypes(include='O')#O=object
catgorical.head()

bike_name       city        owner          brand
0    TVS Star City Plus Dual Tone 110cc  Ahmedabad  First Owner            TVS
1           Royal Enfield Classic 350cc      Delhi  First Owner  Royal Enfield
2                  Triumph Daytona 675R      Delhi  First Owner        Triumph
3                  TVS Apache RTR 180cc  Bangalore  First Owner            TVS
4  Yamaha FZ S V 2.0 150cc-Ltd. Edition  Bangalore  First Owner         Yamaha

In [305]:
numerical=df.select_dtypes(exclude="O")
numerical.head()

price  kms_driven  age  power
0   35000.0     17654.0  3.0  110.0
1  119900.0     11000.0  4.0  350.0
2  600000.0       110.0  8.0  675.0
3   65000.0     16329.0  4.0  180.0
4   80000.0     10000.0  3.0  150.0

In [306]:
combined_df=pd.concat([catgorical,numerical],axis='columns')#by default rows so we specify axis='columns
combined_df.head()

bike_name       city        owner  \
0    TVS Star City Plus Dual Tone 110cc  Ahmedabad  First Owner   
1           Royal Enfield Classic 350cc      Delhi  First Owner   
2                  Triumph Daytona 675R      Delhi  First Owner   
3                  TVS Apache RTR 180cc  Bangalore  First Owner   
4  Yamaha FZ S V 2.0 150cc-Ltd. Edition  Bangalore  First Owner   

           brand     price  kms_driven  age  power  
0            TVS   35000.0     17654.0  3.0  110.0  
1  Royal Enfield  119900.0     11000.0  4.0  350.0  
2        Triumph  600000.0       110.0  8.0  675.0  
3            TVS   65000.0     16329.0  4.0  180.0  
4         Yamaha   80000.0     10000.0  3.0  150.0

In [307]:
catgorical.shape

(32648, 4)

In [308]:
numerical.shape

(32648, 4)

drop->Drop specified labels from rows or columns.

Data cleaning ->cleaning unnecessary data for the objective to increase machine lerning model's accuracy

In [309]:
df.drop('bike_name',axis='columns',inplace=True)#by default finds row
df


price       city  kms_driven        owner   age  power  \
0       35000.0  Ahmedabad     17654.0  First Owner   3.0  110.0   
1      119900.0      Delhi     11000.0  First Owner   4.0  350.0   
2      600000.0      Delhi       110.0  First Owner   8.0  675.0   
3       65000.0  Bangalore     16329.0  First Owner   4.0  180.0   
4       80000.0  Bangalore     10000.0  First Owner   3.0  150.0   
...         ...        ...         ...          ...   ...    ...   
32643   39000.0      Delhi     22000.0  First Owner   4.0  100.0   
32644   30000.0     Karnal      6639.0  First Owner   9.0  180.0   
32645   60000.0      Delhi     20373.0  First Owner   6.0  220.0   
32646   15600.0     Jaipur     84186.0  First Owner  16.0  125.0   
32647   22000.0       Pune     60857.0  First Owner  13.0  150.0   

               brand  
0                TVS  
1      Royal Enfield  
2            Triumph  
3                TVS  
4             Yamaha  
...              ...  
32643           Hero  
32644            TVS  
32645          Bajaj  
32646           Hero  
32647          Bajaj  

[32648 rows x 7 columns]

In [311]:
df.drop(['age'],axis='columns')

price       city  kms_driven        owner  power          brand
0       35000.0  Ahmedabad     17654.0  First Owner  110.0            TVS
1      119900.0      Delhi     11000.0  First Owner  350.0  Royal Enfield
2      600000.0      Delhi       110.0  First Owner  675.0        Triumph
3       65000.0  Bangalore     16329.0  First Owner  180.0            TVS
4       80000.0  Bangalore     10000.0  First Owner  150.0         Yamaha
...         ...        ...         ...          ...    ...            ...
32643   39000.0      Delhi     22000.0  First Owner  100.0           Hero
32644   30000.0     Karnal      6639.0  First Owner  180.0            TVS
32645   60000.0      Delhi     20373.0  First Owner  220.0          Bajaj
32646   15600.0     Jaipur     84186.0  First Owner  125.0           Hero
32647   22000.0       Pune     60857.0  First Owner  150.0          Bajaj

[32648 rows x 6 columns]

In [ ]:
df['dummy']="upflairs"
df
#feature engineering #feature varible columns

price       city  kms_driven        owner   age  power  \
0       35000.0  Ahmedabad     17654.0  First Owner   3.0  110.0   
1      119900.0      Delhi     11000.0  First Owner   4.0  350.0   
2      600000.0      Delhi       110.0  First Owner   8.0  675.0   
3       65000.0  Bangalore     16329.0  First Owner   4.0  180.0   
4       80000.0  Bangalore     10000.0  First Owner   3.0  150.0   
...         ...        ...         ...          ...   ...    ...   
32643   39000.0      Delhi     22000.0  First Owner   4.0  100.0   
32644   30000.0     Karnal      6639.0  First Owner   9.0  180.0   
32645   60000.0      Delhi     20373.0  First Owner   6.0  220.0   
32646   15600.0     Jaipur     84186.0  First Owner  16.0  125.0   
32647   22000.0       Pune     60857.0  First Owner  13.0  150.0   

               brand     dummy  
0                TVS  upflairs  
1      Royal Enfield  upflairs  
2            Triumph  upflairs  
3                TVS  upflairs  
4             Yamaha  upflairs  
...              ...       ...  
32643           Hero  upflairs  
32644            TVS  upflairs  
32645          Bajaj  upflairs  
32646           Hero  upflairs  
32647          Bajaj  upflairs  

[32648 rows x 8 columns]

In [ ]:
df['fake_price']=df['price']+1000
df
#feature engineering

price       city  kms_driven        owner   age  power  \
0       35000.0  Ahmedabad     17654.0  First Owner   3.0  110.0   
1      119900.0      Delhi     11000.0  First Owner   4.0  350.0   
2      600000.0      Delhi       110.0  First Owner   8.0  675.0   
3       65000.0  Bangalore     16329.0  First Owner   4.0  180.0   
4       80000.0  Bangalore     10000.0  First Owner   3.0  150.0   
...         ...        ...         ...          ...   ...    ...   
32643   39000.0      Delhi     22000.0  First Owner   4.0  100.0   
32644   30000.0     Karnal      6639.0  First Owner   9.0  180.0   
32645   60000.0      Delhi     20373.0  First Owner   6.0  220.0   
32646   15600.0     Jaipur     84186.0  First Owner  16.0  125.0   
32647   22000.0       Pune     60857.0  First Owner  13.0  150.0   

               brand     dummy  fake_price  
0                TVS  upflairs     36000.0  
1      Royal Enfield  upflairs    120900.0  
2            Triumph  upflairs    601000.0  
3                TVS  upflairs     66000.0  
4             Yamaha  upflairs     81000.0  
...              ...       ...         ...  
32643           Hero  upflairs     40000.0  
32644            TVS  upflairs     31000.0  
32645          Bajaj  upflairs     61000.0  
32646           Hero  upflairs     16600.0  
32647          Bajaj  upflairs     23000.0  

[32648 rows x 9 columns]

In [ ]:
df.drop(['dummy','fake_price'],axis='columns',inplace=True)


In [ ]:
df

price       city  kms_driven        owner   age  power  \
0       35000.0  Ahmedabad     17654.0  First Owner   3.0  110.0   
1      119900.0      Delhi     11000.0  First Owner   4.0  350.0   
2      600000.0      Delhi       110.0  First Owner   8.0  675.0   
3       65000.0  Bangalore     16329.0  First Owner   4.0  180.0   
4       80000.0  Bangalore     10000.0  First Owner   3.0  150.0   
...         ...        ...         ...          ...   ...    ...   
32643   39000.0      Delhi     22000.0  First Owner   4.0  100.0   
32644   30000.0     Karnal      6639.0  First Owner   9.0  180.0   
32645   60000.0      Delhi     20373.0  First Owner   6.0  220.0   
32646   15600.0     Jaipur     84186.0  First Owner  16.0  125.0   
32647   22000.0       Pune     60857.0  First Owner  13.0  150.0   

               brand  
0                TVS  
1      Royal Enfield  
2            Triumph  
3                TVS  
4             Yamaha  
...              ...  
32643           Hero  
32644            TVS  
32645          Bajaj  
32646           Hero  
32647          Bajaj  

[32648 rows x 7 columns]

In [ ]:
df.head()

price       city  kms_driven        owner  age  power          brand
0   35000.0  Ahmedabad     17654.0  First Owner  3.0  110.0            TVS
1  119900.0      Delhi     11000.0  First Owner  4.0  350.0  Royal Enfield
2  600000.0      Delhi       110.0  First Owner  8.0  675.0        Triumph
3   65000.0  Bangalore     16329.0  First Owner  4.0  180.0            TVS
4   80000.0  Bangalore     10000.0  First Owner  3.0  150.0         Yamaha

In [ ]:
df[df['brand']=='KTM']


price        city  kms_driven         owner  age  power brand
33     180000.0        Pune     17700.0   First Owner  4.0  390.0   KTM
35      70000.0      Nashik    100000.0  Second Owner  8.0  200.0   KTM
39     179000.0   Bangalore      3400.0   First Owner  2.0  200.0   KTM
65      94700.0    Baripara     32700.0   First Owner  4.0  200.0   KTM
83     130000.0  Gandhidham     17500.0  Second Owner  4.0  250.0   KTM
...         ...         ...         ...           ...  ...    ...   ...
32541  196700.0      Mumbai     13216.0   First Owner  4.0  390.0   KTM
32560  196700.0      Mumbai     13216.0   First Owner  4.0  390.0   KTM
32579  196700.0      Mumbai     13216.0   First Owner  4.0  390.0   KTM
32598  196700.0      Mumbai     13216.0   First Owner  4.0  390.0   KTM
32636  196700.0      Mumbai     13216.0   First Owner  4.0  390.0   KTM

[1077 rows x 7 columns]

In [ ]:
df.shape

(32648, 7)

duplicated->Return boolean Series denoting duplicate rows.
Considering certain columns is optional.<br>sum->Return the sum of the values over the requested axis.

In [ ]:
df.duplicated().sum()

np.int64(25328)

In [ ]:
df[df.duplicated()]

price       city  kms_driven        owner   age  power  \
19      29900.0      Delhi     20000.0  First Owner   7.0  125.0   
20     120000.0  Bangalore     23000.0  First Owner   3.0  200.0   
21      48000.0     Mumbai     24725.0  First Owner   5.0  150.0   
25      78000.0  Bangalore      9900.0  First Owner   4.0  200.0   
90      71800.0     Mumbai     43500.0  First Owner   7.0  350.0   
...         ...        ...         ...          ...   ...    ...   
32643   39000.0      Delhi     22000.0  First Owner   4.0  100.0   
32644   30000.0     Karnal      6639.0  First Owner   9.0  180.0   
32645   60000.0      Delhi     20373.0  First Owner   6.0  220.0   
32646   15600.0     Jaipur     84186.0  First Owner  16.0  125.0   
32647   22000.0       Pune     60857.0  First Owner  13.0  150.0   

               brand  
19             Bajaj  
20             Bajaj  
21            Suzuki  
25             Bajaj  
90     Royal Enfield  
...              ...  
32643           Hero  
32644            TVS  
32645          Bajaj  
32646           Hero  
32647          Bajaj  

[25328 rows x 7 columns]

drop_duplicates->Return DataFrame with duplicate rows removed.<br>DataFrame with duplicates removed or None if inplace=True.


In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df.shape

(7320, 7)

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df[df['brand']=='KTM']

price        city  kms_driven         owner  age  power brand
33    180000.0        Pune     17700.0   First Owner  4.0  390.0   KTM
35     70000.0      Nashik    100000.0  Second Owner  8.0  200.0   KTM
39    179000.0   Bangalore      3400.0   First Owner  2.0  200.0   KTM
65     94700.0    Baripara     32700.0   First Owner  4.0  200.0   KTM
83    130000.0  Gandhidham     17500.0  Second Owner  4.0  250.0   KTM
...        ...         ...         ...           ...  ...    ...   ...
9070  140000.0  Berhampore      2600.0   First Owner  6.0  200.0   KTM
9195   70000.0       Thane     49347.0   First Owner  9.0  200.0   KTM
9255  135000.0   Bangalore      1050.0   First Owner  3.0  125.0   KTM
9282  139100.0       Delhi     25500.0   First Owner  5.0  390.0   KTM
9348  195000.0      Mumbai      4568.0   First Owner  4.0  390.0   KTM

[375 rows x 7 columns]

In [ ]:
df['brand'].value_counts()

brand
Bajaj              2081
Royal Enfield      1344
Hero               1141
Honda               676
Yamaha              651
TVS                 481
KTM                 375
Suzuki              203
Harley-Davidson      91
Kawasaki             61
Hyosung              52
Mahindra             50
Benelli              46
Triumph              21
Ducati               20
BMW                  10
Jawa                  7
Indian                3
MV                    3
Rajdoot               1
LML                   1
Yezdi                 1
Ideal                 1
Name: count, dtype: int64

In [ ]:
combined_df.duplicated().sum()

np.int64(25324)

In [ ]:
combined_df[combined_df.duplicated()].head()

bike_name       city        owner          brand  \
19              Bajaj Discover 125M      Delhi  First Owner          Bajaj   
20           Bajaj Pulsar RS200 ABS  Bangalore  First Owner          Bajaj   
21           Suzuki Gixxer SF 150cc     Mumbai  First Owner         Suzuki   
25               Bajaj Pulsar NS200  Bangalore  First Owner          Bajaj   
90  Royal Enfield Thunderbird 350cc     Mumbai  First Owner  Royal Enfield   

       price  kms_driven  age  power  
19   29900.0     20000.0  7.0  125.0  
20  120000.0     23000.0  3.0  200.0  
21   48000.0     24725.0  5.0  150.0  
25   78000.0      9900.0  4.0  200.0  
90   71800.0     43500.0  7.0  350.0

In [ ]:
combined_df['brand'].value_counts()

brand
Bajaj              11213
Hero                6368
Royal Enfield       4178
Yamaha              3916
Honda               2108
Suzuki              1464
TVS                 1247
KTM                 1077
Harley-Davidson      737
Kawasaki              79
Hyosung               64
Benelli               56
Mahindra              55
Triumph               26
Ducati                22
BMW                   16
Jawa                  10
MV                     4
Indian                 3
Ideal                  2
Rajdoot                1
Yezdi                  1
LML                    1
Name: count, dtype: int64

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df

price       city  kms_driven        owner  age  power  \
0      35000.0  Ahmedabad     17654.0  First Owner  3.0  110.0   
1     119900.0      Delhi     11000.0  First Owner  4.0  350.0   
2     600000.0      Delhi       110.0  First Owner  8.0  675.0   
3      65000.0  Bangalore     16329.0  First Owner  4.0  180.0   
4      80000.0  Bangalore     10000.0  First Owner  3.0  150.0   
...        ...        ...         ...          ...  ...    ...   
9362   25000.0      Delhi     48587.0  First Owner  8.0  150.0   
9369   35000.0  Bangalore     60000.0  First Owner  9.0  220.0   
9370  450000.0    Jodhpur      3430.0  First Owner  4.0  750.0   
9371  139000.0  Hyderabad     21300.0  First Owner  4.0  400.0   
9372   80000.0  Hyderabad      7127.0  First Owner  5.0  220.0   

                brand  
0                 TVS  
1       Royal Enfield  
2             Triumph  
3                 TVS  
4              Yamaha  
...               ...  
9362             Hero  
9369            Bajaj  
9370  Harley-Davidson  
9371            Bajaj  
9372            Bajaj  

[7320 rows x 7 columns]

In [ ]:
df.drop('bike_name',axis='columns',inplace=True)

In [ ]:
filter_df=df[(df['brand']=="KTM")|(df['brand']=="Jawa")|(df['brand']=="Suzuki")]
filter_df

NameError: name 'df' is not defined

isin->Whether elements in Series are contained in values.<br>
Return a boolean Series showing whether each element in the Series matches an element in the passed sequence of values exactly.

In [ ]:
brand_ls=['KTM','Suzuki','Jawa']
df[df['brand'].isin(brand_ls)]

price       city  kms_driven         owner  age  power   brand
17     48000.0     Mumbai     24725.0   First Owner  5.0  150.0  Suzuki
33    180000.0       Pune     17700.0   First Owner  4.0  390.0     KTM
35     70000.0     Nashik    100000.0  Second Owner  8.0  200.0     KTM
39    179000.0  Bangalore      3400.0   First Owner  2.0  200.0     KTM
49     97000.0      Delhi      4400.0   First Owner  3.0  150.0  Suzuki
...        ...        ...         ...           ...  ...    ...     ...
9195   70000.0      Thane     49347.0   First Owner  9.0  200.0     KTM
9255  135000.0  Bangalore      1050.0   First Owner  3.0  125.0     KTM
9281   63000.0  Bangalore     19100.0   First Owner  5.0  150.0  Suzuki
9282  139100.0      Delhi     25500.0   First Owner  5.0  390.0     KTM
9348  195000.0     Mumbai      4568.0   First Owner  4.0  390.0     KTM

[585 rows x 7 columns]

In [ ]:
City_ls=['Mumbai','Pune','Nashik']
filter_df[filter_df['city'].isin(City_ls)]

NameError: name 'filter_df' is not defined

keys->Return alias for index.

In [ ]:
df['city'].value_counts().keys()

Index(['Delhi', 'Bangalore', 'Mumbai', 'Gurgaon', 'Faridabad', 'Pune',
       'Jaipur', 'Chennai', 'Ahmedabad', 'Ghaziabad',
       ...
       'Uran', 'Phagwara', 'Vastral', 'Bhuj', 'Gangaghat', 'Gadchiroli',
       'Tiruppur', 'Deesa', 'Kathua', 'Vizianagaram'],
      dtype='object', name='city', length=443)

In [ ]:
f['city'].value_counts().keys()

Index(['Mumbai', 'Pune', 'Nashik'], dtype='object', name='city')

In [ ]:
jaipur=df[df['city']=='Jaipur']
jaipur

price    city  kms_driven         owner   age  power            brand
47     28000.0  Jaipur     45000.0   First Owner   2.0  110.0         Mahindra
134    47000.0  Jaipur     70000.0   First Owner   6.0  150.0           Suzuki
166   123600.0  Jaipur      7702.0   First Owner   3.0  350.0    Royal Enfield
189   435000.0  Jaipur      5550.0  Second Owner   7.0  883.0  Harley-Davidson
490    55000.0  Jaipur      2000.0   First Owner   9.0  150.0            Honda
...        ...     ...         ...           ...   ...    ...              ...
9161   41000.0  Jaipur      8000.0   First Owner   6.0  110.0         Mahindra
9187  520000.0  Jaipur       399.0   First Owner   2.0  750.0  Harley-Davidson
9197   90000.0  Jaipur     17000.0   First Owner   7.0  350.0    Royal Enfield
9198   83800.0  Jaipur     21540.0  Second Owner  10.0  350.0    Royal Enfield
9259   37000.0  Jaipur      8030.0   First Owner   4.0  110.0           Yamaha

[299 rows x 7 columns]

In [ ]:
jaipur[jaipur['brand']=='KTM']

price    city  kms_driven        owner  age  power brand
888   147000.0  Jaipur     15000.0  First Owner  6.0  390.0   KTM
4945  200000.0  Jaipur     11700.0  First Owner  4.0  390.0   KTM
4948  175000.0  Jaipur     10880.0  First Owner  4.0  390.0   KTM
6073  190000.0  Jaipur      7902.0  First Owner  2.0  200.0   KTM
6159  135000.0  Jaipur     12507.0  First Owner  4.0  250.0   KTM
6734  128000.0  Jaipur     15000.0  First Owner  4.0  200.0   KTM
7561  150000.0  Jaipur     12500.0  First Owner  4.0  250.0   KTM

In [ ]:
jaipur['brand'].value_counts()

brand
Hero               91
Bajaj              63
Honda              39
TVS                29
Yamaha             27
Royal Enfield      23
KTM                 7
Mahindra            6
Harley-Davidson     6
Suzuki              4
Benelli             2
Kawasaki            1
Hyosung             1
Name: count, dtype: int64

In [ ]:
brand_ls=['KTM','TVS','Suzuki']
jaipur_bike=jaipur[jaipur['brand'].isin(brand_ls)]
jaipur_bike

price    city  kms_driven         owner   age   power   brand
134     47000.0  Jaipur     70000.0   First Owner   6.0   150.0  Suzuki
617   1260000.0  Jaipur     17000.0   First Owner   4.0  1300.0  Suzuki
888    147000.0  Jaipur     15000.0   First Owner   6.0   390.0     KTM
1132    98000.0  Jaipur       749.0   First Owner   1.0   160.0     TVS
1304    63000.0  Jaipur      1639.0   First Owner   4.0   160.0     TVS
2070   185000.0  Jaipur      2845.0   First Owner   3.0   310.0     TVS
2302    19542.0  Jaipur     56592.0   First Owner   9.0   160.0     TVS
3364    30000.0  Jaipur     27000.0   First Owner   6.0   110.0     TVS
3904    51000.0  Jaipur     18314.0   First Owner   7.0   160.0     TVS
3907    47000.0  Jaipur     26000.0   First Owner   8.0   160.0     TVS
3920    26500.0  Jaipur      2342.0   First Owner   9.0   110.0     TVS
3922    26000.0  Jaipur     24000.0   First Owner   7.0   110.0     TVS
3936    70000.0  Jaipur     28112.0   First Owner   4.0   150.0  Suzuki
4063    33000.0  Jaipur     18677.0   First Owner   6.0   100.0     TVS
4368    86000.0  Jaipur     12000.0   First Owner   3.0   180.0     TVS
4369    78000.0  Jaipur     23918.0   First Owner   5.0   200.0     TVS
4371    68000.0  Jaipur     11123.0   First Owner   5.0   160.0     TVS
4607    23000.0  Jaipur     28895.0   First Owner   8.0   100.0     TVS
4851    45000.0  Jaipur     20431.0   First Owner   7.0   160.0     TVS
4886    59900.0  Jaipur     32000.0   First Owner   5.0   180.0     TVS
4945   200000.0  Jaipur     11700.0   First Owner   4.0   390.0     KTM
4948   175000.0  Jaipur     10880.0   First Owner   4.0   390.0     KTM
5970    22000.0  Jaipur     31000.0   First Owner  10.0   110.0     TVS
6068    31000.0  Jaipur     20000.0   First Owner   7.0   100.0     TVS
6073   190000.0  Jaipur      7902.0   First Owner   2.0   200.0     KTM
6075    25000.0  Jaipur     22620.0   First Owner   9.0   100.0     TVS
6076    24000.0  Jaipur     20885.0   First Owner  14.0   180.0     TVS
6159   135000.0  Jaipur     12507.0   First Owner   4.0   250.0     KTM
6301    34000.0  Jaipur     11536.0   First Owner   5.0   100.0     TVS
6310    34000.0  Jaipur      4474.0   First Owner   3.0   100.0     TVS
6415    58000.0  Jaipur     18583.0   First Owner   6.0   180.0     TVS
6596    48000.0  Jaipur     23541.0   First Owner   6.0   150.0  Suzuki
6734   128000.0  Jaipur     15000.0   First Owner   4.0   200.0     KTM
7311    70000.0  Jaipur    207102.0   First Owner   2.0   180.0     TVS
7561   150000.0  Jaipur     12500.0   First Owner   4.0   250.0     KTM
7591    65000.0  Jaipur     26454.0   First Owner   3.0   180.0     TVS
7712    31599.0  Jaipur     19111.0   First Owner   8.0   100.0     TVS
8074    65000.0  Jaipur     12061.0   First Owner   4.0   180.0     TVS
8924    51000.0  Jaipur     23000.0  Second Owner   6.0   160.0     TVS
9157    32000.0  Jaipur     17870.0   First Owner   7.0   110.0     TVS

In [ ]:
jaipur_bike.shape

(40, 7)

In [ ]:
bike_70k=jaipur_bike[jaipur_bike['price']<=70000]
bike_70k.shape

(28, 7)

In [ ]:
bike_70k[(bike_70k['owner']=='First Owner')&(bike_70k['age']<=2)&(bike_70k['power']<=180)]

price    city  kms_driven        owner  age  power brand
7311  70000.0  Jaipur    207102.0  First Owner  2.0  180.0   TVS

sort_values->Sort by the values along either axis.<br>returns DataFrame with sorted values or None if inplace=True.

In [ ]:
jaipur.sort_values(by='price')#accending order

price    city  kms_driven         owner   age   power  \
2696    14000.0  Jaipur     70756.0   First Owner  13.0   100.0   
9029    14000.0  Jaipur     50000.0  Second Owner  19.0   100.0   
3365    15000.0  Jaipur     52391.0   First Owner  15.0   125.0   
2983    15000.0  Jaipur     48000.0   First Owner  17.0   100.0   
4092    15244.0  Jaipur     40320.0   First Owner  15.0   125.0   
...         ...     ...         ...           ...   ...     ...   
189    435000.0  Jaipur      5550.0  Second Owner   7.0   883.0   
2599   445600.0  Jaipur      1500.0   First Owner   5.0   750.0   
7650   478000.0  Jaipur      1234.0   First Owner   3.0   650.0   
9187   520000.0  Jaipur       399.0   First Owner   2.0   750.0   
617   1260000.0  Jaipur     17000.0   First Owner   4.0  1300.0   

                brand  
2696             Hero  
9029             Hero  
3365             Hero  
2983            Bajaj  
4092             Hero  
...               ...  
189   Harley-Davidson  
2599  Harley-Davidson  
7650         Kawasaki  
9187  Harley-Davidson  
617            Suzuki  

[299 rows x 7 columns]

In [ ]:
jaipur.sort_values(by='price',ascending=False)

price    city  kms_driven         owner   age   power  \
617   1260000.0  Jaipur     17000.0   First Owner   4.0  1300.0   
9187   520000.0  Jaipur       399.0   First Owner   2.0   750.0   
7650   478000.0  Jaipur      1234.0   First Owner   3.0   650.0   
2599   445600.0  Jaipur      1500.0   First Owner   5.0   750.0   
189    435000.0  Jaipur      5550.0  Second Owner   7.0   883.0   
...         ...     ...         ...           ...   ...     ...   
4092    15244.0  Jaipur     40320.0   First Owner  15.0   125.0   
2983    15000.0  Jaipur     48000.0   First Owner  17.0   100.0   
3365    15000.0  Jaipur     52391.0   First Owner  15.0   125.0   
9029    14000.0  Jaipur     50000.0  Second Owner  19.0   100.0   
2696    14000.0  Jaipur     70756.0   First Owner  13.0   100.0   

                brand  
617            Suzuki  
9187  Harley-Davidson  
7650         Kawasaki  
2599  Harley-Davidson  
189   Harley-Davidson  
...               ...  
4092             Hero  
2983            Bajaj  
3365             Hero  
9029             Hero  
2696             Hero  

[299 rows x 7 columns]

In [ ]:
print(jaipur.sort_values.__doc__)


        Sort by the values along either axis.

        Parameters
        ----------
        by : str or list of str
            Name or list of names to sort by.

            - if `axis` is 0 or `'index'` then `by` may contain index
              levels and/or column labels.
            - if `axis` is 1 or `'columns'` then `by` may contain column
              levels and/or index labels.
        axis : "{0 or 'index', 1 or 'columns'}", default 0
             Axis to be sorted.
        ascending : bool or list of bool, default True
             Sort ascending vs. descending. Specify list for multiple sort
             orders.  If this is a list of bools, must match the length of
             the by.
        inplace : bool, default False
             If True, perform operation in-place.
        kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, default 'quicksort'
             Choice of sorting algorithm. See also :func:`numpy.sort` for more
             information. `mergesort` 

In [ ]:
city_ls=['Delhi']
d=df[df['city'].isin(city_ls)]
d

price   city  kms_driven         owner  age  power          brand
1     119900.0  Delhi     11000.0   First Owner  4.0  350.0  Royal Enfield
2     600000.0  Delhi       110.0   First Owner  8.0  675.0        Triumph
5      53499.0  Delhi     25000.0   First Owner  6.0  150.0         Yamaha
6      85000.0  Delhi      8200.0   First Owner  3.0  160.0          Honda
7      45000.0  Delhi     12645.0   First Owner  3.0  100.0           Hero
...        ...    ...         ...           ...  ...    ...            ...
9336  220000.0  Delhi      7130.0   First Owner  5.0  320.0         Yamaha
9338  138000.0  Delhi      5000.0   First Owner  5.0  410.0  Royal Enfield
9340   34400.0  Delhi     24513.0  Second Owner  8.0  150.0          Honda
9344   80000.0  Delhi     56968.0   First Owner  8.0  350.0  Royal Enfield
9362   25000.0  Delhi     48587.0   First Owner  8.0  150.0           Hero

[1424 rows x 7 columns]

In [ ]:
v=d.sort_values(by='price',ascending=False).head(10)
v


price   city  kms_driven         owner  age   power            brand
4864  1800000.0  Delhi      2600.0   First Owner  4.0  1000.0              BMW
7671  1550000.0  Delhi      9800.0  Second Owner  6.0  1000.0           Yamaha
3016  1500000.0  Delhi     18000.0   First Owner  4.0  1000.0              BMW
6501  1490000.0  Delhi     12500.0   First Owner  5.0  1200.0           Ducati
6070  1350000.0  Delhi      4600.0   First Owner  3.0   850.0              BMW
7481  1149000.0  Delhi      9875.0   First Owner  6.0  1300.0           Suzuki
7064  1100000.0  Delhi     24000.0   First Owner  4.0   107.0  Harley-Davidson
7595  1070500.0  Delhi       289.0   First Owner  3.0   959.0           Ducati
3007  1000000.0  Delhi      1500.0   First Owner  4.0  1200.0          Triumph
4725   950000.0  Delhi     21000.0   First Owner  8.0  1300.0           Suzuki

to_csv->Write object to a comma-separated values (csv) file.<br>None or str
    If path_or_buf is None, returns the resulting csv format as a string. Otherwise returns None.

In [ ]:
v.to_csv('delhi_top_ten.csv')#creates a csv file and saves it in the pc

In [ ]:
v['brand'].value_counts()

brand
BMW                3
Ducati             2
Suzuki             2
Yamaha             1
Harley-Davidson    1
Triumph            1
Name: count, dtype: int64

In [ ]:
import pandas as pd

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('Used_Bikes.csv')
df.head()

bike_name     price       city  kms_driven  \
0    TVS Star City Plus Dual Tone 110cc   35000.0  Ahmedabad     17654.0   
1           Royal Enfield Classic 350cc  119900.0      Delhi     11000.0   
2                  Triumph Daytona 675R  600000.0      Delhi       110.0   
3                  TVS Apache RTR 180cc   65000.0  Bangalore     16329.0   
4  Yamaha FZ S V 2.0 150cc-Ltd. Edition   80000.0  Bangalore     10000.0   

         owner  age  power          brand  
0  First Owner  3.0  110.0            TVS  
1  First Owner  4.0  350.0  Royal Enfield  
2  First Owner  8.0  675.0        Triumph  
3  First Owner  4.0  180.0            TVS  
4  First Owner  3.0  150.0         Yamaha

isnull->Return a boolean same-sized object indicating if the values are NA.<br>Mask of bool values for each element in DataFrame that indicates whether an element is an NA value.

In [ ]:
df.isnull().sum()

bike_name     0
price         0
city          0
kms_driven    0
owner         0
age           0
power         0
brand         0
dtype: int64

In [ ]:
import numpy as np

In [ ]:
dt={"A":[1,2,3,np.nan,5],#the values should be same for each key
    "B":[7,4,np.nan,9,2],
    "C":[np.nan,8,7,5,6],
    "D":[7,4,1,2,5]}
dt

{'A': [1, 2, 3, nan, 5],
 'B': [7, 4, nan, 9, 2],
 'C': [nan, 8, 7, 5, 6],
 'D': [7, 4, 1, 2, 5]}

In [ ]:
df=pd.DataFrame(dt)
df

A    B    C  D
0  1.0  7.0  NaN  7
1  2.0  4.0  8.0  4
2  3.0  NaN  7.0  1
3  NaN  9.0  5.0  2
4  5.0  2.0  6.0  5

In [ ]:
#missing value handle
df.isnull().sum()

A    1
B    1
C    1
D    0
dtype: int64

In [ ]:
#remove the records
#record fill

In [ ]:
#remove the records 12%
df

A    B    C  D
0  1.0  7.0  NaN  7
1  2.0  4.0  8.0  4
2  3.0  NaN  7.0  1
3  NaN  9.0  5.0  2
4  5.0  2.0  6.0  5

dropna->Remove missing values.

In [ ]:
df.dropna(axis="columns")

D
0  7
1  4
2  1
3  2
4  5

In [ ]:
df.dropna()# drop the rows with null values ,by default rows

A    B    C  D
1  2.0  4.0  8.0  4
4  5.0  2.0  6.0  5

In [ ]:
df.dropna(axis=1)

D
0  7
1  4
2  1
3  2
4  5

fillna->Fill NA/NaN values using the specified method.

In [ ]:
#fill the records
df.fillna(100000,)

A         B         C  D
0       1.0       7.0  100000.0  7
1       2.0       4.0       8.0  4
2       3.0  100000.0       7.0  1
3  100000.0       9.0       5.0  2
4       5.0       2.0       6.0  5

In [ ]:
#df['A'].fillna(10000,inplace=True)
df['A'].fillna(10000)

0        1.0
1        2.0
2        3.0
3    10000.0
4        5.0
Name: A, dtype: float64

In [ ]:
df

A    B    C  D
0  1.0  7.0  NaN  7
1  2.0  4.0  8.0  4
2  3.0  NaN  7.0  1
3  NaN  9.0  5.0  2
4  5.0  2.0  6.0  5


numerical=median,mean<br>
categorical=mode

In [ ]:
df['B'].mean()

np.float64(5.5)

In [ ]:
df['B'].fillna(df['B'].mean())

0    7.0
1    4.0
2    5.5
3    9.0
4    2.0
Name: B, dtype: float64

if data in normal distribution then mean otherwise median

In [ ]:
df=pd.read_csv('Used_Bikes.csv')
df.head()

bike_name     price       city  kms_driven  \
0    TVS Star City Plus Dual Tone 110cc   35000.0  Ahmedabad     17654.0   
1           Royal Enfield Classic 350cc  119900.0      Delhi     11000.0   
2                  Triumph Daytona 675R  600000.0      Delhi       110.0   
3                  TVS Apache RTR 180cc   65000.0  Bangalore     16329.0   
4  Yamaha FZ S V 2.0 150cc-Ltd. Edition   80000.0  Bangalore     10000.0   

         owner  age  power          brand  
0  First Owner  3.0  110.0            TVS  
1  First Owner  4.0  350.0  Royal Enfield  
2  First Owner  8.0  675.0        Triumph  
3  First Owner  4.0  180.0            TVS  
4  First Owner  3.0  150.0         Yamaha

In [ ]:
#group by operation
df['price'].max()

np.float64(1900000.0)

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df['brand'].value_counts()max()

brand
Bajaj              2081
Royal Enfield      1346
Hero               1142
Honda               676
Yamaha              651
TVS                 481
KTM                 375
Suzuki              203
Harley-Davidson      91
Kawasaki             61
Hyosung              53
Mahindra             50
Benelli              46
Triumph              21
Ducati               20
BMW                  10
Jawa                  7
Indian                3
MV                    3
Rajdoot               1
LML                   1
Yezdi                 1
Ideal                 1
Name: count, dtype: int64

groupby->Group DataFrame using a mapper or by a Series of columns.

In [ ]:
group=df.groupby('brand')
group

In [ ]:
group[['price']].max()#maximum price of bikes in each brand 

price
brand                     
BMW              1800000.0
Bajaj             195000.0
Benelli           785000.0
Ducati           1500000.0
Harley-Davidson  1100000.0
Hero              104000.0
Honda             800000.0
Hyosung           493500.0
Ideal             100000.0
Indian           1900000.0
Jawa              223000.0
KTM               860000.0
Kawasaki         1100000.0
LML                 4400.0
MV               1500000.0
Mahindra          175000.0
Rajdoot            75000.0
Royal Enfield     285000.0
Suzuki           1260000.0
TVS               224000.0
Triumph          1300000.0
Yamaha           1550000.0
Yezdi              68000.0

In [ ]:
group[['price']].max()

price
brand                     
BMW              1800000.0
Bajaj             195000.0
Benelli           785000.0
Ducati           1500000.0
Harley-Davidson  1100000.0
Hero              104000.0
Honda             800000.0
Hyosung           493500.0
Ideal             100000.0
Indian           1900000.0
Jawa              223000.0
KTM               860000.0
Kawasaki         1100000.0
LML                 4400.0
MV               1500000.0
Mahindra          175000.0
Rajdoot            75000.0
Royal Enfield     285000.0
Suzuki           1260000.0
TVS               224000.0
Triumph          1300000.0
Yamaha           1550000.0
Yezdi              68000.0

In [ ]:
min_values=group[['price']].min()

reset_index->resets the index values as group gives the specified column as an index  

In [ ]:
min_values.reset_index(inplace=True).sort_values(by='price')

brand     price
13              LML    4400.0
5              Hero    5000.0
19              TVS    5800.0
1             Bajaj    6400.0
18           Suzuki    8000.0
21           Yamaha    9400.0
6             Honda   10000.0
15         Mahindra   17800.0
17    Royal Enfield   33500.0
11              KTM   55000.0
22            Yezdi   68000.0
16          Rajdoot   75000.0
8             Ideal  100000.0
12         Kawasaki  110000.0
2           Benelli  110700.0
7           Hyosung  120000.0
10             Jawa  146000.0
4   Harley-Davidson  250000.0
0               BMW  255000.0
3            Ducati  380000.0
20          Triumph  500000.0
9            Indian  700000.0
14               MV  950000.0

In [ ]:
min_values.sort_values(by='price')


price
brand                    
LML                4400.0
Hero               5000.0
TVS                5800.0
Bajaj              6400.0
Suzuki             8000.0
Yamaha             9400.0
Honda             10000.0
Mahindra          17800.0
Royal Enfield     33500.0
KTM               55000.0
Yezdi             68000.0
Rajdoot           75000.0
Ideal            100000.0
Kawasaki         110000.0
Benelli          110700.0
Hyosung          120000.0
Jawa             146000.0
Harley-Davidson  250000.0
BMW              255000.0
Ducati           380000.0
Triumph          500000.0
Indian           700000.0
MV               950000.0

agg->Performs sepicified operations on each element of a specified column and creates a new column with the result

In [ ]:
group['price'].agg(min_price="min",max_price="max",mean_price="mean")

min_price  max_price    mean_price
brand                                              
BMW               255000.0  1800000.0  6.735000e+05
Bajaj               6400.0   195000.0  4.903128e+04
Benelli           110700.0   785000.0  2.983761e+05
Ducati            380000.0  1500000.0  9.005750e+05
Harley-Davidson   250000.0  1100000.0  4.734291e+05
Hero                5000.0   104000.0  3.068307e+04
Honda              10000.0   800000.0  5.147068e+04
Hyosung           120000.0   493500.0  2.432084e+05
Ideal             100000.0   100000.0  1.000000e+05
Indian            700000.0  1900000.0  1.100000e+06
Jawa              146000.0   223000.0  1.884286e+05
KTM                55000.0   860000.0  1.479469e+05
Kawasaki          110000.0  1100000.0  4.167116e+05
LML                 4400.0     4400.0  4.400000e+03
MV                950000.0  1500000.0  1.266667e+06
Mahindra           17800.0   175000.0  7.005780e+04
Rajdoot            75000.0    75000.0  7.500000e+04
Royal Enfield      33500.0   285000.0  1.118775e+05
Suzuki              8000.0  1260000.0  1.048563e+05
TVS                 5800.0   224000.0  5.765194e+04
Triumph           500000.0  1300000.0  8.125238e+05
Yamaha              9400.0  1550000.0  7.011080e+04
Yezdi              68000.0    68000.0  6.800000e+04

In [ ]:
df['brand'].value_counts().keys()

Index(['Bajaj', 'Royal Enfield', 'Hero', 'Honda', 'Yamaha', 'TVS', 'KTM',
       'Suzuki', 'Harley-Davidson', 'Kawasaki', 'Hyosung', 'Mahindra',
       'Benelli', 'Triumph', 'Ducati', 'BMW', 'Jawa', 'Indian', 'MV',
       'Rajdoot', 'LML', 'Yezdi', 'Ideal'],
      dtype='object', name='brand')

values->Return Series as ndarray or ndarray-like depending on the dtype.

In [ ]:
df['brand'].value_counts().values

array([2081, 1346, 1142,  676,  651,  481,  375,  203,   91,   61,   53,
         50,   46,   21,   20,   10,    7,    3,    3,    1,    1,    1,
          1])

get_group->Construct DataFrame from group with provided name.

In [ ]:
group.get_group('Suzuki')

bike_name    price         city  kms_driven  \
17              Suzuki Gixxer SF 150cc  48000.0       Mumbai     24725.0   
49    Suzuki Gixxer SF Fi 150cc SP ABS  97000.0        Delhi      4400.0   
58                 Suzuki Gixxer 150cc  30200.0    Bangalore     45000.0   
96          Suzuki Gixxer Fi 150cc ABS  96700.0     Vadodara      5100.0   
105   Suzuki Gixxer 150cc SP Rear Disc  65000.0     Thrissur     41000.0   
...                                ...      ...          ...         ...   
8808               Suzuki Gixxer 150cc  50000.0    Hyderabad     35053.0   
8973               Suzuki Hayate 110cc  25000.0        Delhi     10000.0   
8983               Suzuki Gixxer 150cc  58000.0       Mumbai      6000.0   
9025       Suzuki Slingshot Plus 125cc  40000.0  Pondicherry      5000.0   
9281  Suzuki Gixxer SF 150cc Rear Disc  63000.0    Bangalore     19100.0   

            owner  age  power   brand  
17    First Owner  5.0  150.0  Suzuki  
49    First Owner  3.0  150.0  Suzuki  
58    First Owner  7.0  150.0  Suzuki  
96    First Owner  1.0  150.0  Suzuki  
105   First Owner  3.0  150.0  Suzuki  
...           ...  ...    ...     ...  
8808  First Owner  5.0  150.0  Suzuki  
8973  First Owner  7.0  110.0  Suzuki  
8983  First Owner  5.0  150.0  Suzuki  
9025  First Owner  6.0  125.0  Suzuki  
9281  First Owner  5.0  150.0  Suzuki  

[203 rows x 8 columns]

In [ ]:
owner_group=df.groupby('owner')
owner_group

In [ ]:
owner_group[['price']].min()

price
owner                        
First Owner            4400.0
Fourth Owner Or More  11000.0
Second Owner           7500.0
Third Owner            7000.0

In [ ]:
owner_group[['price']].max()

price
owner                          
First Owner           1900000.0
Fourth Owner Or More   141000.0
Second Owner          1550000.0
Third Owner            699000.0

In [ ]:
bajaj=df[df['brand']=='Bajaj']#owners only for brand bajaj
bajaj_group=bajaj.groupby('owner')
bajaj_group['price'].agg(min_price='min',max_price='max',mean_price='mean')


min_price  max_price    mean_price
owner                                                   
First Owner              6400.0   195000.0  49915.159664
Fourth Owner Or More    11000.0    37000.0  24000.000000
Second Owner             9000.0   140000.0  41056.980769
Third Owner              7000.0    85000.0  28565.736842

In [ ]:
owner_group['price'].agg(min_price='min',max_price='max',mean_price='mean')

min_price  max_price    mean_price
owner                                                   
First Owner              4400.0  1900000.0  85044.934207
Fourth Owner Or More    11000.0   141000.0  62699.000000
Second Owner             7500.0  1550000.0  83653.561224
Third Owner              7000.0   699000.0  83404.130952

In [ ]:
df['owner'].value_counts()

owner
First Owner             6642
Second Owner             588
Third Owner               84
Fourth Owner Or More      10
Name: count, dtype: int64

In [ ]:
label={'First Owner':1,
       'Second Owner':2,
       'Third Owner':3,
       'Fourth Owner Or More':4}
label

{'First Owner': 1,
 'Second Owner': 2,
 'Third Owner': 3,
 'Fourth Owner Or More': 4}

map->Map values of Series according to an input mapping or function.

In [ ]:
df['owner']=df['owner'].map(label)

In [ ]:
df['owner']

0       1
1       1
2       1
3       1
4       1
       ..
9362    1
9369    1
9370    1
9371    1
9372    1
Name: owner, Length: 7324, dtype: int64

In [ ]:
df['owner'].value_counts()

owner
1    6642
2     588
3      84
4      10
Name: count, dtype: int64