<h>Numpy</h>
<p>Numpy->It is an essential python library used to perform operation especially on array</p>

In [96]:
import numpy as np
print("numpy is imported")


numpy is imported


<p>np.array->used to create an array from a list</p>

In [97]:
ls=[41,52,63]
arr=np.array(ls)
arr

array([41, 52, 63])

<p>type->used for getting the type of datastructure like list ,tuple, dictionary ,sets of the variable</p>

In [98]:
type(arr)

numpy.ndarray

In [99]:
arr*5000000

array([205000000, 260000000, 315000000])

<p>arr.ndim->used for tracing out the dimention of the array</p>

In [100]:
arr.ndim #no of dimension

1

<p>dtype->for getting the datatype of the variable</p>

In [101]:
arr.dtype

dtype('int64')

In [102]:
ls=[41,52,63,12.3]
arr=np.array(ls)
arr

array([41. , 52. , 63. , 12.3])

In [103]:
ls=[41,52,63,'upflairs']
arr=np.array(ls)
arr

array(['41', '52', '63', 'upflairs'], dtype='<U21')

In [104]:
ls=[41,52,63]
arr=np.array(ls)
arr

array([41, 52, 63])

In [105]:
arr[2] # index_address=first_address+(size_datatype*index_number)

np.int64(63)

In [106]:
ls=[41,52,63,96,85,74,5,32,52,63,46,2,52,63,1]
arr=np.array(ls)
arr

array([41, 52, 63, 96, 85, 74,  5, 32, 52, 63, 46,  2, 52, 63,  1])

In [107]:
for i in range(len(arr)):
    if arr[i]<50:
         arr[i]

In [108]:
arr[arr<50]

array([41,  5, 32, 46,  2,  1])

<p>shape->for getting the shape of array in form of rows and columns</h>

In [109]:
arr.shape

(15,)

<p>arrange->for getting 1d array in range specfied in the argument</p>

In [110]:
arr2=np.arange(50)#1d
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

<p>ones->for making n dimentional array having only 1 as an element</p>

In [111]:
np.ones((10,5,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

zeroes->for making an nd array with 0 as an element

In [112]:
np.zeros((10,5,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

linespace->for making nd array with elements between the given range with specified number of parts

In [113]:
np.linspace(1,8,5)

array([1.  , 2.75, 4.5 , 6.25, 8.  ])

random->a library in python for grtting random values.Random variable generators.

In [114]:
import random

randint()->Return random integer in range [a, b], including both end points.



In [115]:
random.randint(1,10)

8

random->Returns the values between 0 and 1.

In [116]:
random.random()

0.18133135810132295

In [117]:
ls=['arushi','nikita','pragati','yasmeen','princy','kartik','ronak']

choice->Choose a random element from a non-empty sequence.

In [118]:
random.choice(ls)#for single item

'nikita'

choices->Return a k sized list of population elements chosen with replacement.<br>
If the relative weights or cumulative weights are not specified, the selections are made with equal probability.

In [119]:
random.choices(ls,k=2)

['nikita', 'nikita']

In [120]:
ls

['arushi', 'nikita', 'pragati', 'yasmeen', 'princy', 'kartik', 'ronak']

shuffle->Shuffle list x in place, and return None.

In [121]:
random.shuffle(ls)
ls

['yasmeen', 'kartik', 'arushi', 'pragati', 'ronak', 'nikita', 'princy']

In [122]:
np.random.randint(1,50,10)

array([31,  1, 30, 24, 42,  1, 47, 34, 25, 45], dtype=int32)

In [123]:
!python --version 

Python 3.11.9


In [124]:
import numpy as np
np.random.randint(1,50,(10,2))

array([[38,  9],
       [45, 41],
       [41, 47],
       [46, 34],
       [34, 16],
       [28, 33],
       [20, 11],
       [ 2, 30],
       [34, 30],
       [37, 10]], dtype=int32)

In [125]:
arr=np.arange(60)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

reshape->reshape the array keeping the number of elements the same<br>changes the values of m and n such that the multiplication remains the same

In [126]:
arr.reshape(15,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47],
       [48, 49, 50, 51],
       [52, 53, 54, 55],
       [56, 57, 58, 59]])

resize->Return a new array with the specified shape.
If the new array is larger than the original array, then the new array is filled with repeated copies of arrar. Note that this behavior is different from a.resize(new_shape) which fills with zeros instead of repeated copies of array.

In [127]:
arr2=np.resize(arr,(25,25))
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,
         6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
        31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59,  0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
        21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45,
        46, 47, 48, 49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10,
        11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 

In [128]:
arr2.shape

(25, 25)

In [129]:
arr2.ndim

2

In [130]:
arr2.reshape(625,)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,  6,  7,
        8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
       25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58,
       59,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
       16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54, 55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,  6,
        7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
       24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
       41, 42, 43, 44, 45

ravel->changes the dimension of the array to 1d array

In [131]:
arr2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,  6,  7,
        8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
       25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58,
       59,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
       16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54, 55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,  6,
        7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
       24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
       41, 42, 43, 44, 45

In [132]:
import numpy as np

In [133]:
arr=np.random.randint(5,50,100)
arr

array([12, 44, 39, 37, 34, 38,  7, 19, 12, 31, 30, 11,  7, 19, 23, 34,  6,
       31, 12,  8, 36, 39, 10, 16, 15, 24,  5, 49, 39, 37, 34, 46, 32, 24,
        7,  9, 21, 30, 15, 45, 33, 12, 46, 21, 49, 12, 37, 20, 14, 16, 34,
        8, 19, 32, 35, 21, 27, 32, 26,  7, 27, 40,  5,  8, 46, 44, 36, 46,
       34, 24, 32, 42, 39, 25,  9, 49, 17, 31, 25, 16, 33, 35, 35,  9, 13,
       24, 18,  8, 49, 30,  6, 29, 43, 23, 16, 44, 24, 13, 32, 32],
      dtype=int32)

min->Returns the minimum element of the array

In [134]:
arr.min()

np.int32(5)

max->Returns the maximum element of the array

In [135]:
arr.max()

np.int32(49)

sum->Returns the sum of all the elements of the array 

In [136]:
arr.sum()

np.int64(2599)

mean->Returns the mean value of the array

In [137]:
arr.mean() #mean=average

np.float64(25.99)

In [138]:
arr=np.random.randint(5,50,(4,3))
arr

array([[13, 38, 36],
       [11, 42,  8],
       [25,  7, 26],
       [38, 34, 40]], dtype=int32)

In [139]:
arr.shape

(4, 3)

transpose->gives the transpose of the nd array

In [140]:
np.transpose(arr)

array([[13, 11, 25, 38],
       [38, 42,  7, 34],
       [36,  8, 26, 40]], dtype=int32)

In [141]:
np.transpose(arr).shape

(3, 4)

In [142]:
arr.T #same as transpose

array([[13, 11, 25, 38],
       [38, 42,  7, 34],
       [36,  8, 26, 40]], dtype=int32)

In [143]:
arr=np.random.randint(2,12,(10,5))
arr

array([[ 5,  7,  4,  4,  5],
       [11, 10,  6,  9,  6],
       [10,  6,  9,  4,  5],
       [ 5,  5,  5,  7, 10],
       [ 8,  2,  3,  9,  2],
       [ 2,  6, 10, 10,  5],
       [ 2,  8, 10,  2,  5],
       [ 6,  6,  8,  4, 11],
       [ 7,  7,  6,  3,  8],
       [ 3,  8,  5, 11,  2]], dtype=int32)

flatten->converts the nd array into 1d array

In [144]:
arr.flatten()

array([ 5,  7,  4,  4,  5, 11, 10,  6,  9,  6, 10,  6,  9,  4,  5,  5,  5,
        5,  7, 10,  8,  2,  3,  9,  2,  2,  6, 10, 10,  5,  2,  8, 10,  2,
        5,  6,  6,  8,  4, 11,  7,  7,  6,  3,  8,  3,  8,  5, 11,  2],
      dtype=int32)

In [145]:
arr.ravel()

array([ 5,  7,  4,  4,  5, 11, 10,  6,  9,  6, 10,  6,  9,  4,  5,  5,  5,
        5,  7, 10,  8,  2,  3,  9,  2,  2,  6, 10, 10,  5,  2,  8, 10,  2,
        5,  6,  6,  8,  4, 11,  7,  7,  6,  3,  8,  3,  8,  5, 11,  2],
      dtype=int32)

In [146]:
arr.reshape(50,)

array([ 5,  7,  4,  4,  5, 11, 10,  6,  9,  6, 10,  6,  9,  4,  5,  5,  5,
        5,  7, 10,  8,  2,  3,  9,  2,  2,  6, 10, 10,  5,  2,  8, 10,  2,
        5,  6,  6,  8,  4, 11,  7,  7,  6,  3,  8,  3,  8,  5, 11,  2],
      dtype=int32)

In [147]:
np.resize(arr,(50,))

array([ 5,  7,  4,  4,  5, 11, 10,  6,  9,  6, 10,  6,  9,  4,  5,  5,  5,
        5,  7, 10,  8,  2,  3,  9,  2,  2,  6, 10, 10,  5,  2,  8, 10,  2,
        5,  6,  6,  8,  4, 11,  7,  7,  6,  3,  8,  3,  8,  5, 11,  2],
      dtype=int32)

In [148]:
arr.reshape(10,5)

array([[ 5,  7,  4,  4,  5],
       [11, 10,  6,  9,  6],
       [10,  6,  9,  4,  5],
       [ 5,  5,  5,  7, 10],
       [ 8,  2,  3,  9,  2],
       [ 2,  6, 10, 10,  5],
       [ 2,  8, 10,  2,  5],
       [ 6,  6,  8,  4, 11],
       [ 7,  7,  6,  3,  8],
       [ 3,  8,  5, 11,  2]], dtype=int32)

In [149]:
arr[0]

array([5, 7, 4, 4, 5], dtype=int32)

In [150]:
arr[-1,0]

np.int32(3)

In [151]:
arr[2:5]

array([[10,  6,  9,  4,  5],
       [ 5,  5,  5,  7, 10],
       [ 8,  2,  3,  9,  2]], dtype=int32)

In [152]:
arr[7:10]

array([[ 6,  6,  8,  4, 11],
       [ 7,  7,  6,  3,  8],
       [ 3,  8,  5, 11,  2]], dtype=int32)

In [153]:
arr[7:10,0:2]

array([[6, 6],
       [7, 7],
       [3, 8]], dtype=int32)

In [154]:
arr[0:10,0:2]

array([[ 5,  7],
       [11, 10],
       [10,  6],
       [ 5,  5],
       [ 8,  2],
       [ 2,  6],
       [ 2,  8],
       [ 6,  6],
       [ 7,  7],
       [ 3,  8]], dtype=int32)

In [155]:
arr[0:,0:2]

array([[ 5,  7],
       [11, 10],
       [10,  6],
       [ 5,  5],
       [ 8,  2],
       [ 2,  6],
       [ 2,  8],
       [ 6,  6],
       [ 7,  7],
       [ 3,  8]], dtype=int32)

In [156]:
arr[-5:-2,-3:]

array([[10, 10,  5],
       [10,  2,  5],
       [ 8,  4, 11]], dtype=int32)

In [157]:
arr[0::2,2:6:2]

array([[ 4,  5],
       [ 9,  5],
       [ 3,  2],
       [10,  5],
       [ 6,  8]], dtype=int32)

In [158]:
import numpy as np
import random
arr=np.random.randint(2,50,(5,10,5))
arr


array([[[39,  9,  7,  6, 43],
        [39, 11, 41, 30, 49],
        [28, 32, 39, 22, 24],
        [ 6, 45, 18,  9, 39],
        [18, 43, 34, 23,  2],
        [28, 34, 32, 35, 20],
        [27, 12, 48, 15, 38],
        [17, 32, 44,  9, 29],
        [46, 34, 27, 15, 18],
        [ 4, 20, 20, 32, 40]],

       [[37, 26,  4, 23, 44],
        [ 5, 15, 46,  6, 13],
        [ 5,  7, 23, 45, 46],
        [40, 46,  8,  4, 36],
        [18, 31, 17,  4, 36],
        [26, 36, 39,  5, 11],
        [18, 12, 16, 37, 29],
        [31, 35, 15, 17, 11],
        [20, 32,  5, 35, 28],
        [23, 48, 41,  8, 49]],

       [[44, 24, 14, 21, 11],
        [15, 15, 23,  9, 23],
        [18, 14, 28, 17,  9],
        [45, 37, 24,  3, 25],
        [25, 15,  6, 43, 41],
        [12, 48, 44, 16, 34],
        [18, 15, 20, 38, 37],
        [ 3, 17, 49,  9, 40],
        [46, 41,  9, 47,  5],
        [48, 41, 26, 10, 23]],

       [[42,  4, 13, 44, 25],
        [23, 29, 18, 29, 10],
        [18, 25, 23, 11, 17],
    

In [159]:
arr.shape

(5, 10, 5)

In [160]:
arr.ndim

3

In [161]:
arr[0]

array([[39,  9,  7,  6, 43],
       [39, 11, 41, 30, 49],
       [28, 32, 39, 22, 24],
       [ 6, 45, 18,  9, 39],
       [18, 43, 34, 23,  2],
       [28, 34, 32, 35, 20],
       [27, 12, 48, 15, 38],
       [17, 32, 44,  9, 29],
       [46, 34, 27, 15, 18],
       [ 4, 20, 20, 32, 40]], dtype=int32)

In [162]:
arr[0,8:,2:]

array([[27, 15, 18],
       [20, 32, 40]], dtype=int32)

In [163]:
arr[:6:,9,0:6]

array([[ 4, 20, 20, 32, 40],
       [23, 48, 41,  8, 49],
       [48, 41, 26, 10, 23],
       [35, 40, 11, 43, 21],
       [ 3, 15, 46, 23, 35]], dtype=int32)

In [164]:
arr=np.array([7,5,9])
arr

array([7, 5, 9])

In [165]:
arr.argsort()

array([1, 0, 2])

In [166]:
arr.max()

np.int64(9)

argmax->shows the index of maximum item

In [167]:
arr.argmax()#shows the index of maximum item

np.int64(2)

argmin->shows the index of minimum item

In [168]:
arr.argmin()#shows the index of minimum item

np.int64(1)

sort->sort the array in-place and returns none

In [169]:
arr.sort()

In [170]:
arr

array([5, 7, 9])

argsort->returns the original index of the elements after sorting and returns a list

In [171]:
arr.argsort()

array([0, 1, 2])

In [172]:
arr

array([5, 7, 9])

In [173]:
arr=np.random.randint(2,12,(10,5))
arr

array([[ 8, 10, 11,  7, 11],
       [10,  7, 10, 10,  4],
       [ 6, 10,  5,  5,  3],
       [ 7,  2, 10,  3,  9],
       [ 6, 10,  6,  4,  9],
       [11,  2,  2,  5, 11],
       [ 7,  6,  5,  6, 11],
       [ 9,  4,  5,  2,  3],
       [10,  7,  5,  9,  7],
       [ 6,  2,  4, 10,  5]], dtype=int32)

In [174]:
arr=[1,2,2,3,3,4,5,6]

unique->returns the unique elements of the array in an array

In [175]:
np.unique(arr)

array([1, 2, 3, 4, 5, 6])

In [176]:
np.random.randint(2,250,200)

array([  4,   9, 172, 131, 153, 148, 116, 174,  62, 128, 230, 132,  95,
        32, 197,  47, 220, 213, 153, 239,  93, 176, 230, 131,  61, 190,
       147, 111,  52,  54, 147, 158, 124, 236,   8, 116, 105, 169, 215,
        99, 135, 102, 189,  89, 221,  11,  61,  91,  21, 136,  23, 239,
       231, 205, 235, 221,   6, 180,  91, 191, 122,  81, 195, 223, 116,
       168, 160,  75, 222, 212,  29, 205, 170, 166, 196,  98, 189,  40,
       117, 226, 160, 118, 162,  83, 152, 229, 191,  74, 131, 135, 196,
        42, 187, 167,  48, 213,  80, 215, 175,  53, 207, 172,  80, 127,
       206, 205, 249, 192,  35,  31, 246,  21,  59, 182,  90, 175, 239,
       159, 175,  78, 167, 129, 178, 206, 228, 195,  22,  20,  79,   6,
        98, 179,   5,  23, 193, 209, 171,  87, 162, 170, 138,  54, 248,
        87,  13,  11, 210, 115, 138,   5, 213,  56,  28, 227, 160,   4,
       166, 198, 246, 231, 224,  80, 172,  66, 241, 148, 148, 151, 141,
        69, 103,  39,  26,  28, 146,   6, 110,  62, 236,  52,  1

median->Returns the median of the array

In [177]:
np.median(arr)

np.float64(3.0)

var->Returns the varience of the elements in the array

In [178]:
np.var(arr)

np.float64(2.4375)

std->returns the standard deviation of the array which is square root of varience

In [179]:
np.std(arr)

np.float64(1.5612494995995996)

sqrt->Returns the square root of array

In [180]:
np.sqrt(25)

np.float64(5.0)

In [181]:
#pandas

In [182]:
!pip install pandas


[notice] A new release of pip is available: 24.0 -> 24.1.2
[notice] To update, run: C:\Users\DeLL\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [183]:
!pip install pandas


[notice] A new release of pip is available: 24.0 -> 24.1.2
[notice] To update, run: C:\Users\DeLL\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


pandas->It is an essential library in python used in data science helps to read relational files or tabular form of database files like exel-csv,sql etc

In [184]:
import pandas as pd
print("imported")

imported


In [185]:
dt = {"Name":['Nikita rawat','pragati sharama','kartik','arushi'],
     "Branch":['cse','it','ece','cse'],
     "class":[1,2,3,4],
     "city":['ajmer','agra','mathura','vridavan']}
dt




{'Name': ['Nikita rawat', 'pragati sharama', 'kartik', 'arushi'],
 'Branch': ['cse', 'it', 'ece', 'cse'],
 'class': [1, 2, 3, 4],
 'city': ['ajmer', 'agra', 'mathura', 'vridavan']}

DataFrame->Two-dimensional, size-mutable, potentially heterogeneous tabular data.<br>The primary pandas data structure.

In [186]:
dt=pd.DataFrame(dt)
dt


Name Branch  class      city
0     Nikita rawat    cse      1     ajmer
1  pragati sharama     it      2      agra
2           kartik    ece      3   mathura
3           arushi    cse      4  vridavan

In [187]:
type(dt)

pandas.core.frame.DataFrame

In [188]:
dt["Name"]

0       Nikita rawat
1    pragati sharama
2             kartik
3             arushi
Name: Name, dtype: object

In [189]:
type(dt["Name"])

pandas.core.series.Series

read_csv->reads file with csv extension.<br>There are more types of files which can be read but we are working with csv file

In [190]:
df= pd.read_csv('Used_Bikes.csv')
df

FileNotFoundError: [Errno 2] No such file or directory: 'Used_Bikes.csv'

head->Return the first n rows.<br>by default returns first 5

In [ ]:
df.head(20)

NameError: name 'df' is not defined

tail->Return the last n rows.<br>by default returns the last 5 rows

In [ ]:
df.tail(10)

NameError: name 'df' is not defined

info->Print a concise summary of a DataFrame.<br>
This method prints information about a DataFrame including the index dtype and columns, non-null values and memory usage.

In [ ]:
df.info()

NameError: name 'df' is not defined

In [ ]:
## accessing
df.price

: 

In [ ]:
df["price"]

: 

In [ ]:
type(df['price'])

: 

In [ ]:
df[["price"]]#dataframe

: 

In [ ]:
df[['price','city','brand']]

: 

loc->Access a group of rows and columns by label(s) or a boolean array.


In [ ]:
#loc & iloc
df.loc[10:20,['price','bike_name']]

: 

In [ ]:
df.loc[20:35,['owner','age','power','brand']]

: 

In [ ]:
df

: 

iloc->Purely integer-location based indexing for selection by position
disadvantage->it can only access the columns in range not from betwwen like loc

In [ ]:
df.iloc[20:35,0:3:2]

: 

min->Return the minimum of the values over the requested axis.



In [ ]:
df['price'].min()

: 

max->Return the maximum of the values over the requested axis.

In [ ]:
df['price'].max()

: 

mean->Return the mean of the values over the requested axis.

In [ ]:
df['price'].mean()

: 

median->Return the median of the values over the requested axis.

In [ ]:
df['price'].median()

: 

columns->returns all th column values

In [ ]:
df.columns

: 

In [ ]:
df.columns=['bike_name', 'price', 'city', 'kms_driven', 'owner', 'age', 'power',
      'brand']
df.columns

: 

In [ ]:
df.shape#no of rows and no of columns

: 

In [ ]:
df.dtypes #datatypes of each column

: 

In [ ]:
udr_50k=df[df['price']<=50000]
udr_50k.head()#by default 5
     

: 

In [ ]:
udr_50k['price'].max()

: 

In [ ]:
udr_50k.shape

: 

value_counts->Return a Series containing counts of unique values.

In [ ]:
udr_50k['brand'].value_counts()

: 

In [ ]:
udr_50k['owner'].value_counts()

: 

In [ ]:
udr_50k_first=udr_50k[udr_50k['owner']=="First Owner"]
udr_50k_first.head()

: 

In [ ]:
udr_50k_first[['price']].min()

: 

In [ ]:
udr_50k_first[udr_50k_first['price']==4400]

: 

In [ ]:
udr_50k_first['brand'].value_counts()

: 

unique->Return unique values of Series object.

In [ ]:
udr_50k_first['brand'].unique()

: 

nunique->Return number of unique elements in the object.<br>
Excludes NA values by default.

In [ ]:
udr_50k_first['brand'].nunique()

: 

In [ ]:
df['brand'].nunique()

: 

In [ ]:
df['brand'].unique()

: 

&->returns true if all the conditions are true

In [ ]:
dt=df[(df['price']<=100000)&(df['owner']=='First Owner') & (df['age']<=2)&(df['brand']=="Bajaj")]
dt


: 

In [ ]:
dt['brand'].value_counts()

: 

In [ ]:
import pandas as pd
df= pd.read_csv('Used_Bikes.csv')
df

: 

In [ ]:
df.head()

: 

In [ ]:
#
df.dtypes
#numerical and categorical

: 

In [ ]:
df[['price','kms_driven','age','power']]

: 

select_dtypes->Return a subset of the DataFrame's columns based on the column dtypes.

In [ ]:
catgorical=df.select_dtypes(include='O')#O=object
catgorical.head()

: 

In [ ]:
numerical=df.select_dtypes(exclude="O")
numerical.head()

: 

In [ ]:
combined_df=pd.concat([catgorical,numerical],axis='columns')#by default rows so we specify axis='columns
combined_df.head()

: 

In [ ]:
catgorical.shape

: 

In [ ]:
numerical.shape

: 

drop->Drop specified labels from rows or columns.

In [ ]:
df.drop('bike_name',axis='columns',inplace=True)#by default finds row
df


: 

In [ ]:
df.drop(['age','bike_name'],axis='columns')

: 

In [ ]:
df['dummy']="upflairs"
df
#feature engineering #feature varible columns

: 

In [ ]:
df['fake_price']=df['price']+1000
df
#feature engineering

: 

In [ ]:
df.drop(['dummy','fake_price'],axis='columns',inplace=True)


: 

In [ ]:
df

: 

In [ ]:
df.head()

: 

In [ ]:
df[df['brand']=='KTM']


: 

In [ ]:
df.shape

: 

duplicated->Return boolean Series denoting duplicate rows.
Considering certain columns is optional.<br>sum->Return the sum of the values over the requested axis.

In [ ]:
df.duplicated().sum()

: 

In [ ]:
df[df.duplicated()]

: 

drop_duplicates->Return DataFrame with duplicate rows removed.<br>DataFrame with duplicates removed or None if inplace=True.


In [ ]:
df.drop_duplicates(inplace=True)

: 

In [ ]:
df.shape

: 

In [ ]:
df.duplicated().sum()

: 

In [ ]:
df[df['brand']=='KTM']

: 

In [ ]:
df['brand'].value_counts()

: 

In [ ]:
combined_df.duplicated().sum()

: 

In [ ]:
combined_df[combined_df.duplicated()].head()

: 

In [ ]:
combined_df['brand'].value_counts()

: 

In [ ]:
df.drop_duplicates(inplace=True)

: 

In [ ]:
df

: 

In [ ]:
df.drop('bike_name',axis='columns',inplace=True)

: 

In [ ]:
filter_df=df[(df['brand']=="KTM")|(df['brand']=="Jawa")|(df['brand']=="Suzuki")]
filter_df

: 

isin->Whether elements in Series are contained in values.<br>
Return a boolean Series showing whether each element in the Series matches an element in the passed sequence of values exactly.

In [ ]:
brand_ls=['KTM','Suzuki','Jawa']
df[df['brand'].isin(brand_ls)]

: 

In [ ]:
City_ls=['Mumbai','Pune','Nashik']
filter_df[filter_df['city'].isin(City_ls)]

: 

keys->Return alias for index.

In [ ]:
df['city'].value_counts().keys()

: 

In [ ]:
f['city'].value_counts().keys()

: 

In [ ]:
jaipur=df[df['city']=='Jaipur']
jaipur

: 

In [ ]:
jaipur[jaipur['brand']=='KTM']

: 

In [ ]:
jaipur['brand'].value_counts()

: 

In [ ]:
brand_ls=['KTM','TVS','Suzuki']
jaipur_bike=jaipur[jaipur['brand'].isin(brand_ls)]
jaipur_bike

: 

In [ ]:
jaipur_bike.shape

: 

In [ ]:
bike_70k=jaipur_bike[jaipur_bike['price']<=70000]
bike_70k.shape

: 

In [ ]:
bike_70k[(bike_70k['owner']=='First Owner')&(bike_70k['age']<=2)&(bike_70k['power']<=180)]

: 

sort_values->Sort by the values along either axis.<br>returns DataFrame with sorted values or None if inplace=True.

In [ ]:
jaipur.sort_values(by='price')#accending order

: 

In [ ]:
jaipur.sort_values(by='price',ascending=False)

: 

In [ ]:
print(jaipur.sort_values.__doc__)

: 

In [ ]:
city_ls=['Delhi']
d=df[df['city'].isin(city_ls)]
d

: 

In [ ]:
v=d.sort_values(by='price',ascending=False).head(10)
v


: 

to_csv->Write object to a comma-separated values (csv) file.<br>None or str
    If path_or_buf is None, returns the resulting csv format as a string. Otherwise returns None.

In [ ]:
v.to_csv('delhi_top_ten.csv')#creates a csv file and saves it in the pc

: 

In [ ]:
v['brand'].value_counts()

: 

In [ ]:
import pandas as pd

: 

In [ ]:
import pandas as pd

: 

In [ ]:
df=pd.read_csv('Used_Bikes.csv')
df.head()

: 

isnull->Return a boolean same-sized object indicating if the values are NA.<br>Mask of bool values for each element in DataFrame that indicates whether an element is an NA value.

In [ ]:
df.isnull().sum()

: 

In [ ]:
import numpy as np

: 

In [ ]:
dt={"A":[1,2,3,np.nan,5],#the values should be same for each key
    "B":[7,4,np.nan,9,2],
    "C":[np.nan,8,7,5,6],
    "D":[7,4,1,2,5]}
dt

: 

In [ ]:
df=pd.DataFrame(dt)
df

: 

In [ ]:
#missing value handle
df.isnull().sum()

: 

In [ ]:
#remove the records
#record fill

: 

In [ ]:
#remove the records 12%
df

: 

dropna->Remove missing values.

In [ ]:
df.dropna(axis="columns")

: 

In [ ]:
df.dropna()# drop the rows with null values ,by default rows

: 

In [ ]:
df.dropna(axis=1)

: 

fillna->Fill NA/NaN values using the specified method.

In [ ]:
#fill the records
df.fillna(100000,)

: 

In [ ]:
#df['A'].fillna(10000,inplace=True)
df['A'].fillna(10000)

: 

In [ ]:
df

: 


numerical=median,mean<br>
categorical=mode

In [ ]:
df['B'].mean()

: 

In [ ]:
df['B'].fillna(df['B'].mean())

: 

if data in normal distribution then mean otherwise median

In [ ]:
df=pd.read_csv('Used_Bikes.csv')
df.head()

: 

In [ ]:
#group by operation
df['price'].max()

: 

In [ ]:
df.drop_duplicates(inplace=True)

: 

In [ ]:
df['brand'].value_counts()max()

: 

groupby->Group DataFrame using a mapper or by a Series of columns.

In [ ]:
group=df.groupby('brand')
group

: 

In [ ]:
group[['price']].max()#maximum price of bikes in each brand 

: 

In [ ]:
group[['price']].max()

: 

In [ ]:
min_values=group[['price']].min()

: 

reset_index->resets the index values as group gives the specified column as an index  

In [ ]:
min_values.reset_index(inplace=True).sort_values(by='price')

: 

In [ ]:
min_values.sort_values(by='price')


: 

agg->Performs sepicified operations on each element of a specified column and creates a new column with the result

In [ ]:
group['price'].agg(min_price="min",max_price="max",mean_price="mean")

: 

In [ ]:
df['brand'].value_counts().keys()

: 

values->Return Series as ndarray or ndarray-like depending on the dtype.

In [ ]:
df['brand'].value_counts().values

: 

get_group->Construct DataFrame from group with provided name.

In [ ]:
group.get_group('Suzuki')

: 

In [ ]:
owner_group=df.groupby('owner')
owner_group

: 

In [ ]:
owner_group[['price']].min()

: 

In [ ]:
owner_group[['price']].max()

: 

In [ ]:
bajaj=df[df['brand']=='Bajaj']#owners only for brand bajaj
bajaj_group=bajaj.groupby('owner')
bajaj_group['price'].agg(min_price='min',max_price='max',mean_price='mean')


: 

In [ ]:
owner_group['price'].agg(min_price='min',max_price='max',mean_price='mean')

: 

In [ ]:
df['owner'].value_counts()

: 

In [ ]:
label={'First Owner':1,
       'Second Owner':2,
       'Third Owner':3,
       'Fourth Owner Or More':4}
label

: 

map->Map values of Series according to an input mapping or function.

In [ ]:
df['owner']=df['owner'].map(label)

: 

In [ ]:
df['owner']

: 

In [ ]:
df['owner'].value_counts()

: 